fn main() {
    for file in [
        "main.slint",
        "theme.slint",
        "components.slint",
        "i18n.slint",
        "expert_widgets.slint",
        "expert_data.slint",
        "channels_page.slint",
        "thread_log.slint",
        "cron_page.slint",
        "entity_pages.slint",
        "tools_page.slint",
        "tools_widgets.slint",
        "tools_theme.slint",
        "composer.slint",
        "timeline.slint",
        "markdown.slint",
        "patch_diff_card.slint",
        "workflow_detail.slint",
        "runtime_status.slint",
        "tray.slint",
        "tray-notice.slint",
        "screenshot_overlay.slint",
    ] {
        println!("cargo:rerun-if-changed=ui/{file}");
    }
    // Composer tool glyphs are embedded straight from disk, so an icon-only
    // edit must also invalidate the generated resource table.
    for icon in [
        "microphone.svg",
        "camera.svg",
        "stop.svg",
        "paper-plane.svg",
        "wand-magic-sparkles.svg",
    ] {
        println!("cargo:rerun-if-changed=assets/icons/{icon}");
    }
    println!("cargo:rerun-if-changed=assets/fonts/msyh.ttc");
    let raw = std::fs::read("assets/fonts/msyh.ttc").expect("read bundled Microsoft YaHei");
    let compressed = lz4_flex::compress_prepend_size(&raw);
    let out_dir = std::path::PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(out_dir.join("msyh.ttc.lz4"), compressed)
        .expect("write compressed Microsoft YaHei");
    generate_file_icons(&out_dir);
    generate_avatar_assets(&out_dir);
    embed_windows_exe_icon();
    slint_build::compile_with_config(
        "ui/main.slint",
        slint_build::CompilerConfiguration::new()
            .with_style("fluent".into())
            .embed_resources(slint_build::EmbedResourcesKind::EmbedFiles),
    )
    .expect("failed to compile Slint UI");
}

/// Rasterize the web-aligned workspace icon set (assets synced by
/// `scripts/sync_desktop_file_icons.py`) into PNG textures and emit
/// `file_icons_data.rs` with the embedded bytes plus the extension/file-name
/// lookup tables used by the runtime resolver.
fn generate_file_icons(out_dir: &std::path::Path) {
    println!("cargo:rerun-if-changed=assets/vscode-icons");
    println!("cargo:rerun-if-changed=assets/doc-icons");
    let map: serde_json::Value = serde_json::from_str(
        &String::from_utf8(read_required("assets/vscode-icons/file-icon-map.json"))
            .expect("parse file-icon-map.json"),
    )
    .expect("parse file-icon-map.json");
    let default_icon = icon_value(&map["default"]);
    let folder_icon = icon_value(&map["folder"]);
    let diagram_icon = icon_value(&map["diagram"]);

    let mut referenced: Vec<String> = vec![default_icon.clone()];
    for table in ["extensions", "names"] {
        for value in map[table].as_object().expect("icon table").values() {
            referenced.push(icon_value(value));
        }
    }
    referenced.sort();
    referenced.dedup();
    for name in &referenced {
        let key = png_key(name);
        let svg = read_required(&format!("assets/vscode-icons/{name}"));
        write_texture(out_dir, &key, &rasterize_svg(&svg));
    }
    for name in [&folder_icon, &diagram_icon] {
        let bytes = read_required(&format!("assets/doc-icons/{name}"));
        write_texture(out_dir, name, &bytes);
    }

    let mut data = String::from(
        "// @generated by build.rs from assets/vscode-icons/file-icon-map.json;\n\
         // re-sync via scripts/sync_desktop_file_icons.py. Do not edit.\n",
    );
    data.push_str("pub(crate) static ICON_BYTES: &[(&str, &[u8])] = &[\n");
    for name in &referenced {
        let key = png_key(name);
        data.push_str(&format!("    ({key:?}, include_bytes!({key:?})),\n"));
    }
    for name in [&folder_icon, &diagram_icon] {
        data.push_str(&format!("    ({name:?}, include_bytes!({name:?})),\n"));
    }
    data.push_str("];\n");
    emit_table(&mut data, "EXTENSIONS", &map["extensions"], true);
    emit_table(&mut data, "NAMES", &map["names"], true);
    emit_table(
        &mut data,
        "DIAGRAM_EXTENSIONS",
        &map["diagram-extensions"],
        false,
    );
    data.push_str(&format!(
        "pub(crate) const DEFAULT_ICON: &str = {:?};\n\
         pub(crate) const FOLDER_ICON: &str = {:?};\n\
         pub(crate) const DIAGRAM_ICON: &str = {:?};\n",
        png_key(&default_icon),
        png_key(&folder_icon),
        png_key(&diagram_icon),
    ));
    std::fs::write(out_dir.join("file_icons_data.rs"), data).expect("write file_icons_data.rs");
}

/// Embed the web-aligned static agent avatar catalog
/// (`assets/agent-avatars/avatar-NNN.png`, synced from the web client) and
/// emit `avatar_assets_data.rs` with the numeric-ordered key table.
fn generate_avatar_assets(out_dir: &std::path::Path) {
    println!("cargo:rerun-if-changed=assets/agent-avatars");
    let dir = std::path::Path::new("assets/agent-avatars");
    let mut files: Vec<String> = std::fs::read_dir(dir)
        .expect("read agent-avatars directory")
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name().to_string_lossy().to_string())
        .filter(|name| {
            name.starts_with("avatar-")
                && (name.ends_with(".png") || name.ends_with(".jpg") || name.ends_with(".jpeg"))
        })
        .collect();
    files.sort_by_key(|name| {
        name.trim_end_matches(".png")
            .trim_end_matches(".jpeg")
            .trim_end_matches(".jpg")
            .trim_start_matches("avatar-")
            .parse::<u32>()
            .unwrap_or(u32::MAX)
    });
    if files.is_empty() {
        panic!("assets/agent-avatars must contain avatar-NNN images");
    }
    let mut data = String::from(
        "// @generated by build.rs from assets/agent-avatars; do not edit.\n\
         pub(crate) static AVATAR_FILES: &[(&str, &[u8])] = &[\n",
    );
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir");
    for name in &files {
        // The table is `include!`d from OUT_DIR, so relative paths would resolve
        // against OUT_DIR; anchor each texture to the manifest instead.
        data.push_str(&format!(
            "    ({key:?}, include_bytes!(concat!(\
                {manifest:?}, \"/assets/agent-avatars/{name}\"\
            ))),\n",
            key = avatar_key(name),
            manifest = manifest_dir,
        ));
    }
    data.push_str("];\n");
    std::fs::write(out_dir.join("avatar_assets_data.rs"), data).expect("write avatar table");
}

/// `avatar-046.png` -> `avatar-046`, mirroring the web catalog keys.
fn avatar_key(file_name: &str) -> String {
    file_name
        .trim_end_matches(".png")
        .trim_end_matches(".jpeg")
        .trim_end_matches(".jpg")
        .to_string()
}

fn emit_table(data: &mut String, name: &str, value: &serde_json::Value, keyed: bool) {
    if keyed {
        let mut rows: Vec<(String, String)> = value
            .as_object()
            .expect("keyed icon table")
            .iter()
            .map(|(key, value)| (key.clone(), icon_value(value)))
            .collect();
        rows.sort_by(|a, b| a.0.cmp(&b.0));
        data.push_str(&format!("pub(crate) static {name}: &[(&str, &str)] = &[\n"));
        for (key, icon) in rows {
            data.push_str(&format!("    ({key:?}, {:?}),\n", png_key(&icon)));
        }
    } else {
        let mut items: Vec<String> = value
            .as_array()
            .expect("icon list")
            .iter()
            .map(|item| item.as_str().expect("icon key").to_owned())
            .collect();
        items.sort();
        data.push_str(&format!("pub(crate) static {name}: &[&str] = &[\n"));
        for item in items {
            data.push_str(&format!("    {item:?},\n"));
        }
    }
    data.push_str("];\n");
}

fn icon_value(value: &serde_json::Value) -> String {
    value.as_str().expect("icon file name").to_owned()
}

/// Icon table keys reference textures by their PNG name.
fn png_key(icon: &str) -> String {
    match icon.strip_suffix(".svg") {
        Some(stem) => format!("{stem}.png"),
        None => icon.to_owned(),
    }
}

fn read_required(path: &str) -> Vec<u8> {
    std::fs::read(path).unwrap_or_else(|error| panic!("read {path}: {error}"))
}

fn write_texture(out_dir: &std::path::Path, key: &str, bytes: &[u8]) {
    std::fs::write(out_dir.join(key), bytes).unwrap_or_else(|error| panic!("write {key}: {error}"));
}

/// Render an SVG at 2x so the software renderer downscales crisply at the
/// 12-20px sizes the file lists use. resvg outputs premultiplied alpha; the
/// runtime decodes straight alpha, so convert before encoding.
fn rasterize_svg(svg: &[u8]) -> Vec<u8> {
    let tree = resvg::usvg::Tree::from_data(svg, &resvg::usvg::Options::default())
        .expect("parse workspace icon svg");
    let size = tree.size();
    let scale = 2.0f32;
    let width = (size.width() * scale).round() as u32;
    let height = (size.height() * scale).round() as u32;
    let mut pixmap = resvg::tiny_skia::Pixmap::new(width, height).expect("icon pixmap");
    resvg::render(
        &tree,
        resvg::tiny_skia::Transform::from_scale(scale, scale),
        &mut pixmap.as_mut(),
    );
    let mut straight = pixmap.data().to_vec();
    for pixel in straight.chunks_exact_mut(4) {
        let alpha = pixel[3];
        if alpha == 0 {
            pixel[..3].fill(0);
        } else if alpha != 255 {
            for channel in &mut pixel[..3] {
                *channel = (((*channel as u32) * 255 + alpha as u32 / 2) / alpha as u32) as u8;
            }
        }
    }
    let mut encoded = Vec::new();
    let mut encoder = png::Encoder::new(&mut encoded, width, height);
    encoder.set_color(png::ColorType::Rgba);
    encoder.set_depth(png::BitDepth::Eight);
    encoder
        .write_header()
        .expect("png header")
        .write_image_data(&straight)
        .expect("png data");
    encoded
}

/// Embed the app icon (`images/beeroom.ico`, multi-size BMP-style entries
/// that old binutils windres handles) as the exe's icon resource plus a
/// VERSIONINFO block built from the crate version so Explorer's file
/// properties show the release number. Resource-only COFF objects from
/// windres link cleanly into the GNU (Win7 i686) binary. This must key off
/// the *target* OS, not the host: cross builds (ARM64 Linux -> i686 Win7) run
/// this build script on Linux. If windres is unavailable the build continues
/// without file resources; the runtime window icon from app-icon.rgba still
/// covers the title bar and taskbar.
fn embed_windows_exe_icon() {
    let target = std::env::var("TARGET").unwrap_or_default();
    if !target.contains("windows") {
        return;
    }
    println!("cargo:rerun-if-env-changed=WUNDER_WIN7_MINGW_BIN");
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir");
    let ico = std::path::Path::new(&manifest_dir)
        .join("..")
        .join("images")
        .join("beeroom.ico");
    println!("cargo:rerun-if-changed={}", ico.display());

    // windres -F takes a BFD target name; the "pei-*" names are PE *image*
    // formats (MZ/DOS stub included) and cannot be linked as objects. The
    // linkable COFF object formats are "pe-*".
    let format = if target.contains("i686") {
        "pe-i386"
    } else {
        "pe-x86-64"
    };
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let rc_path = std::path::Path::new(&out_dir).join("app-icon.rc");
    let obj_path = std::path::Path::new(&out_dir).join("app-icon.o");

    // Keep the strings ASCII-only: the GNU windres in the Win7 kit reads the
    // script in the console codepage, so non-ASCII text would be mangled.
    let version = std::env::var("CARGO_PKG_VERSION").expect("package version");
    let mut parts = version
        .split('.')
        .map(|part| part.parse::<u16>().unwrap_or(0));
    let version_commas = format!(
        "{},{},{},0",
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0)
    );
    let rc = format!(
        "1 ICON \"{icon}\"\r\n\
         1 VERSIONINFO\r\n\
         FILEVERSION {version_commas}\r\n\
         PRODUCTVERSION {version_commas}\r\n\
         FILEOS 0x40004\r\n\
         FILETYPE 0x1\r\n\
         BEGIN\r\n\
           BLOCK \"StringFileInfo\"\r\n\
           BEGIN\r\n\
             BLOCK \"080404b0\"\r\n\
             BEGIN\r\n\
               VALUE \"CompanyName\", \"wunder\"\r\n\
               VALUE \"FileDescription\", \"wunder Slint Workbench\"\r\n\
               VALUE \"FileVersion\", \"{version}\"\r\n\
               VALUE \"InternalName\", \"wunder-frontend-slint\"\r\n\
               VALUE \"OriginalFilename\", \"wunder-frontend-slint.exe\"\r\n\
               VALUE \"ProductName\", \"wunder-frontend-slint\"\r\n\
               VALUE \"ProductVersion\", \"{version}\"\r\n\
             END\r\n\
           END\r\n\
           BLOCK \"VarFileInfo\"\r\n\
           BEGIN\r\n\
             VALUE \"Translation\", 0x804, 0x4b0\r\n\
           END\r\n\
         END\r\n",
        icon = ico.display().to_string().replace('\\', "/"),
        version_commas = version_commas,
        version = version
    );
    std::fs::write(&rc_path, rc).expect("write resource rc");

    let mut candidates: Vec<std::path::PathBuf> = Vec::new();
    if let Ok(mingw) = std::env::var("WUNDER_WIN7_MINGW_BIN") {
        candidates.push(std::path::Path::new(&mingw).join("windres.exe"));
        // The Linux cross SDK installs this wrapper name (no .exe suffix).
        candidates.push(std::path::Path::new(&mingw).join("i686-w64-mingw32-windres"));
    }
    candidates.push(std::path::PathBuf::from("i686-w64-mingw32-windres"));
    candidates.push(std::path::PathBuf::from("windres"));
    candidates.push(std::path::PathBuf::from(r"C:\mingw64\bin\windres.exe"));
    candidates.push(std::path::PathBuf::from(
        r"C:\mingw32-12.2-winlibs\mingw32\bin\windres.exe",
    ));
    let windres = candidates.iter().find(|candidate| {
        std::process::Command::new(candidate)
            .arg("--version")
            .output()
            .map(|output| output.status.success())
            .unwrap_or(false)
    });
    let Some(windres) = windres else {
        println!("cargo:warning=windres not found; exe file resources not embedded");
        return;
    };
    let status = std::process::Command::new(windres)
        .arg("-F")
        .arg(format)
        .arg("-i")
        .arg(&rc_path)
        .arg("-o")
        .arg(&obj_path)
        .status()
        .expect("run windres");
    if !status.success() {
        println!("cargo:warning=windres failed; exe file resources not embedded");
        return;
    }
    println!("cargo:rustc-link-arg={}", obj_path.display());
}
