// 页面状态集中管理，避免跨模块重复声明
export const state = {
  runtime: {
    activeController: null,
    monitorPollTimer: null,
    debugPollTimer: null,
    memoryPollTimer: null,
    activePanel: "monitor",
    debugSessionId: "",
    debugSessionStatus: "",
    debugSessionPinned: false,
    debugStreaming: false,
    promptReloadTimer: null,
    promptNeedsRefresh: false,
    promptReloadHandler: null,
  },
  panelLoaded: {
    monitor: false,
    users: false,
    userAccounts: false,
    externalLinks: false,
    presetAgents: false,
    companions: false,
    orgUnits: false,
    memory: false,
    interlink: false,
    channels: false,
    throughput: false,
    performance: false,
    evaluation: false,
    multimodalDebug: false,
    docsSite: false,
    mcp: false,
    lsp: false,
    a2aServices: false,
    builtin: false,
    skills: false,
    toolVisibility: false,
    knowledge: false,
    llm: false,
    cloud: false,
  },
  companions: {
    items: [],
    selectedId: "",
    search: "",
    loading: false,
  },
  performance: {
    running: false,
    samples: [],
    history: [],
  },
  multimodalDebug: {
    loaded: false,
    busy: false,
    lastResult: null,
    previewObjectUrl: null,
  },
  mcp: {
    servers: [],
    toolsByIndex: [],
    selectedIndex: -1,
    saveVersion: 0,
    lastAction: null,
    selectedTool: null,
  },
  lsp: {
    config: null,
    status: [],
  },
  a2aServices: {
    services: [],
    selectedIndex: -1,
    saveVersion: 0,
  },
  channels: {
    accounts: [],
    selectedIndex: -1,
    filters: {
      keyword: "",
      status: "",
      activity: "",
      issueOnly: false,
    },
  },
  a2aServiceModal: {
    index: null,
  },
  mcpModal: {
    index: null,
  },
  skills: {
    skills: [],
    paths: [],
    detailVersion: 0,
    visibilityRules: [],
  },
  knowledge: {
    bases: [],
    selectedIndex: -1,
    files: [],
    activeFile: "",
    fileContent: "",
    vectorDocs: [],
    activeDocId: "",
    docContent: "",
    docMeta: null,
    docChunks: [],
    selectedChunkIndices: new Set(),
    embeddingChunkIndices: new Set(),
    embeddingModels: [],
  },
  builtin: {
    tools: [],
    visibilityRules: [],
  },
  toolVisibility: {
    tools: [],
    selectedName: "",
    visibilityRules: [],
  },
  toolSelection: {
    builtin: [],
    mcp: [],
    a2a: [],
    skills: [],
    knowledge: [],
    userTools: [],
    sharedTools: [],
    selected: new Set(),
    loaded: false,
  },
  userTools: {
    modal: {
      activeTab: "mcp",
    },
    mcp: {
      servers: [],
      toolsByIndex: [],
      selectedIndex: -1,
      saveVersion: 0,
      loaded: false,
      lastAction: null,
    },
    skills: {
      skills: [],
      enabled: [],
      shared: [],
      detailVersion: 0,
      loaded: false,
      lastAction: null,
    },
    knowledge: {
      bases: [],
      selectedIndex: -1,
      files: [],
      activeFile: "",
      fileContent: "",
      loaded: false,
    },
  },
  llm: {
    configs: {},
    order: [],
    defaultName: "",
    defaultEmbeddingName: "",
    defaultAsrName: "",
    defaultTtsName: "",
    defaultImageName: "",
    defaultVideoName: "",
    activeName: "",
    nameEdits: {},
    virtualLogs: [],
    virtualLogsLoaded: false,
    loaded: false,
  },
  workspace: {
    path: "",
    parent: null,
    entries: [],
    selected: null,
    selectedPaths: new Set(),
    lastSelectedPath: "",
    expanded: new Set(),
    sortBy: "name",
    sortOrder: "asc",
    searchKeyword: "",
    searchMode: false,
    renamingPath: "",
    treeVersion: 0,
    flatEntries: [],
    previewEntry: null,
  },
  monitor: {
    sessions: [],
    selected: null,
    detail: null,
    tokenTrend: [],
    tokenDeltas: [],
    tokenUsageBySession: {},
    toolStats: [],
    availableTools: [],
    availableToolsUpdatedAt: 0,
    userFilter: "",
    sessionStatusFilter: "all",
    feedbackFilter: "all",
    timeRangeHours: 3,
    serviceSnapshot: null,
    pagination: {
      pageSize: 100,
      activePage: 1,
    },
    timeFilter: {
      enabled: false,
      start: "",
      end: "",
    },
  },
  users: {
    list: [],
    selectedId: "",
    loaded: false,
    updatedAt: 0,
    summary: null,
    summaryUpdatedAt: 0,
    search: "",
    pagination: {
      pageSize: 100,
      page: 1,
    },
  },
  userAccounts: {
    list: [],
    selectedId: "",
    loaded: false,
    search: "",
    pagination: {
      pageSize: 50,
      page: 1,
      total: 0,
    },
    toolAccess: {},
  },
  // 云端接入（设备 / 调用记账 / 设备日志）；子视图由 web/modules/cloud.js 惰性初始化
  cloud: {
    activeTab: "devices",
    devices: null,
    calls: null,
    logs: null,
  },
  externalLinks: {
    list: [],
    selectedId: "",
    loaded: false,
    loading: false,
  },
  orgUnits: {
    list: [],
    tree: [],
    selectedId: "",
    loaded: false,
    lastUpdated: 0,
    collapsed: new Set(),
  },
  memory: {
    users: [],
    records: [],
    selectedId: "",
    enabled: false,
    search: "",
    pagination: {
      pageSize: 100,
      page: 1,
    },
    status: {
      active: [],
      history: [],
      updatedAt: "",
      updatedAtTs: 0,
    },
    queuePagination: {
      pageSize: 100,
      activePage: 1,
      historyPage: 1,
    },
    queueDetailId: "",
    queueDetail: null,
    editingRecord: null,
    loaded: false,
  },
};
