// 页面状态集中管理，避免跨模块重复声明
export const state = {
  runtime: {
    activeController: null,
    monitorPollTimer: null,
    debugPollTimer: null,
    memoryPollTimer: null,
    throughputPollTimer: null,
    activePanel: "monitor",
    debugSessionId: "",
    debugSessionStatus: "",
    debugEventCursor: 0,
    debugRestored: false,
    debugStreaming: false,
    debugSyncAfterStream: false,
    debugSawFinal: false,
    throughputHistoryMode: false,
    throughputHistoryRunId: "",
    promptReloadTimer: null,
    promptNeedsRefresh: false,
    promptReloadHandler: null,
    llmOutput: {
      globalRound: 0,
      currentRound: null,
      // 模型输出按轮次拆分的运行时状态      rounds: [],
      selectedRound: null,
      userSelectedRound: false,
    },
  },
  panelLoaded: {
    monitor: false,
    users: false,
    userAccounts: false,
    memory: false,
    throughput: false,
    performance: false,
    evaluation: false,
    mcp: false,
    lsp: false,
    a2aServices: false,
    builtin: false,
    skills: false,
    knowledge: false,
    llm: false,
  },
  performance: {
    running: false,
    samples: [],
    history: [],
  },
  mcp: {
    servers: [],
    toolsByIndex: [],
    selectedIndex: -1,
    saveVersion: 0,
    lastAction: null,
    selectedTool: null,
  },
  lsp: {
    config: null,
    status: [],
  },
  a2aServices: {
    services: [],
    selectedIndex: -1,
    saveVersion: 0,
  },
  a2aServiceModal: {
    index: null,
  },
  mcpModal: {
    index: null,
  },
  skills: {
    skills: [],
    paths: [],
    detailVersion: 0,
  },
  knowledge: {
    bases: [],
    selectedIndex: -1,
    files: [],
    activeFile: "",
    fileContent: "",
  },
  builtin: {
    tools: [],
  },
  toolSelection: {
    builtin: [],
    mcp: [],
    a2a: [],
    skills: [],
    knowledge: [],
    userTools: [],
    sharedTools: [],
    selected: new Set(),
    loaded: false,
  },
  userTools: {
    extraPrompt: "",
    modal: {
      activeTab: "mcp",
    },
    mcp: {
      servers: [],
      toolsByIndex: [],
      selectedIndex: -1,
      saveVersion: 0,
      loaded: false,
      lastAction: null,
    },
    skills: {
      skills: [],
      enabled: [],
      shared: [],
      detailVersion: 0,
      loaded: false,
      lastAction: null,
    },
    knowledge: {
      bases: [],
      selectedIndex: -1,
      files: [],
      activeFile: "",
      fileContent: "",
      loaded: false,
    },
  },
  llm: {
    configs: {},
    order: [],
    defaultName: "",
    activeName: "",
    nameEdits: {},
    loaded: false,
  },
  workspace: {
    path: "",
    parent: null,
    entries: [],
    selected: null,
    selectedPaths: new Set(),
    lastSelectedPath: "",
    expanded: new Set(),
    sortBy: "name",
    sortOrder: "asc",
    searchKeyword: "",
    searchMode: false,
    renamingPath: "",
    treeVersion: 0,
    flatEntries: [],
    previewEntry: null,
  },
  monitor: {
    sessions: [],
    selected: null,
    tokenTrend: [],
    tokenDeltas: [],
    tokenUsageBySession: {},
    toolStats: [],
    availableTools: [],
    availableToolsUpdatedAt: 0,
    userFilter: "",
    timeRangeHours: 3,
    serviceSnapshot: null,
    pagination: {
      pageSize: 100,
      activePage: 1,
      historyPage: 1,
    },
    timeFilter: {
      enabled: false,
      start: "",
      end: "",
    },
  },
  users: {
    list: [],
    selectedId: "",
    loaded: false,
    updatedAt: 0,
    summary: null,
    summaryUpdatedAt: 0,
    search: "",
    pagination: {
      pageSize: 100,
      page: 1,
    },
  },
  userAccounts: {
    list: [],
    selectedId: "",
    loaded: false,
    search: "",
    pagination: {
      pageSize: 50,
      page: 1,
      total: 0,
    },
    toolAccess: {},
  },
  memory: {
    users: [],
    records: [],
    selectedId: "",
    enabled: false,
    search: "",
    pagination: {
      pageSize: 100,
      page: 1,
    },
    status: {
      active: [],
      history: [],
      updatedAt: "",
      updatedAtTs: 0,
    },
    queuePagination: {
      pageSize: 100,
      activePage: 1,
      historyPage: 1,
    },
    queueDetailId: "",
    queueDetail: null,
    editingRecord: null,
    loaded: false,
  },
};
