# -*- coding: utf-8 -*-
"""Build ui/i18n.slint from scripts/catalog/*.py and validate coverage.

- Catalog entries: (key, zh, en) or (key, zh, en, params) for a parameterized
  formatter. Keys are unique; zh matches UI literals, with `{}` where a
  parameter is substituted.
- Validates that every CJK literal in ui/*.slint has a catalog entry.
- Writes ui/i18n.slint (generated, do not edit by hand) and ui-i18n.json
  (consumed by build.rs to generate the Rust-side text table).
"""
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from slint_scan import has_cjk, scan  # noqa: E402

CATALOG_DIR = os.path.join(HERE, "catalog")
ROOT = os.path.dirname(HERE)
SKIP_FILES = {"design_tokens.slint", "i18n.slint"}


def load_catalog():
    entries = []
    seen_keys = {}
    for name in sorted(os.listdir(CATALOG_DIR)):
        if not name.endswith(".py"):
            continue
        namespace = {}
        with open(os.path.join(CATALOG_DIR, name), encoding="utf-8") as fh:
            exec(compile(fh.read(), name, "exec"), namespace)
        for entry in namespace.get("ENTRIES", []):
            key, zh, en = entry[0], entry[1], entry[2]
            params = list(entry[3]) if len(entry) > 3 else []
            if key in seen_keys:
                raise SystemExit(f"duplicate key {key} in {name} and {seen_keys[key]}")
            seen_keys[key] = name
            entries.append((key, zh, en, params))
    return entries


def slint_strings():
    found = {}
    for path in sorted(glob.glob(os.path.join(ROOT, "ui", "*.slint"))):
        base = os.path.basename(path)
        if base in SKIP_FILES:
            continue
        source = open(path, encoding="utf-8").read()
        for _start, _end, text in scan(source):
            if has_cjk(text) and text not in found:
                found[text] = base
    return found


def main():
    entries = load_catalog()
    zh_map = {}
    for key, zh, _en, _params in entries:
        zh_map.setdefault(zh, key)
    ui_strings = slint_strings()
    missing = sorted(zh for zh in ui_strings if zh not in zh_map)
    if missing:
        print("MISSING catalog entries for UI strings:")
        for zh in missing:
            print(f"  [{ui_strings[zh]}] {zh!r}")
        sys.exit(1)
    used = {zh_map[zh] for zh in ui_strings}
    rust_only = [e for e in entries if e[0] not in used]
    lines = [
        "// GENERATED by frontend-slint/scripts/build_i18n.py from scripts/catalog/*.py.",
        "// Do not edit by hand: add or change entries in the catalog and rebuild.",
        "export global I18n {",
        "    in-out property <bool> zh: true;",
    ]
    for key, zh, en, params in entries:
        if not params:
            lines.append(f'    out property <string> {key}: zh ? "{zh}" : "{en}";')
            continue
        # Parameterized entries become pure formatters: `{}` in the catalog
        # text is replaced by the matching argument.
        signature = ", ".join(f"{name}: string" for name in params)
        body_zh, body_en = zh, en
        for index, name in enumerate(params):
            body_zh = body_zh.replace("{}", '" + ' + name + ' + "', 1)
            body_en = body_en.replace("{}", '" + ' + name + ' + "', 1)
        lines.append(
            f'    public pure function {key}({signature}) -> string '
            f'{{ return zh ? "{body_zh}" : "{body_en}"; }}'
        )
    lines.append("}")
    out_path = os.path.join(ROOT, "ui", "i18n.slint")
    with open(out_path, "w", encoding="utf-8", newline="") as fh:
        fh.write("\n".join(lines) + "\n")
    with open(os.path.join(ROOT, "ui-i18n.json"), "w", encoding="utf-8", newline="") as fh:
        json.dump(
            [
                {"key": k, "zh": z, "en": e, **({"params": p} if p else {})}
                for k, z, e, p in entries
            ],
            fh,
            ensure_ascii=False,
            indent=1,
        )
    print(f"catalog entries: {len(entries)} (slint-referenced: {len(used)}, rust-only: {len(rust_only)})")
    print("wrote", out_path)


if __name__ == "__main__":
    main()
