import { getCurrentLanguage } from "../i18n.js?v=20260710-01";

const copy = {
  title: ["吞吐量测试", "Model throughput"],
  subtitle: ["一次测试一个模型与长度组合，积累结果，比较性能变化。", "Test one model and length combination, then compare results over time."],
  scenario: ["测试配置", "Test configuration"],
  model: ["选择模型", "Model"], input: ["注入的上文", "Input context"], output: ["输出 Token", "Output tokens"],
  inputHint: ["1k = 1,024 Token。输入为预估长度，实测以 API 用量为准。", "1k = 1,024 tokens. Input length is estimated; API usage provides actual counts."],
  outputHint: ["支持的推理引擎强制定长输出；其他 API 设置输出上限并检查是否达标。", "Supported engines enforce fixed output. Other APIs receive a limit; actual output is checked."],
  privacy: ["仅保留最近 50 次性能摘要，不创建用户、会话或线程日志。", "Only the latest 50 performance summaries are retained. No users, sessions or thread logs are created."],
  start: ["开始测试", "Start test"], stop: ["停止测试", "Stop test"], stopping: ["正在停止", "Stopping"],
  refresh: ["刷新", "Refresh"], export: ["导出所选数据", "Export selected"],
  details: ["测试详情", "Test details"], empty: ["选择模型和 Token 长度，开始第一次测试。", "Select a model and token lengths to start your first test."],
  current: ["查看当前测试", "View current test"], historical: ["历史结果", "Historical result"],
  running: ["测试中", "Running"], finished: ["已达标", "Target reached"], incomplete: ["未达标 / 待核验", "Incomplete / unverified"], error: ["失败", "Failed"], stopped: ["已停止", "Stopped"], idle: ["等待测试", "Ready"],
  ttft: ["首字延迟", "Time to first token"], decode: ["生成速度", "Generation speed"], elapsed: ["总耗时", "Total duration"],
  actualInput: ["实际输入 Token", "Actual input tokens"], actualOutput: ["实际输出 Token", "Actual output tokens"],
  estimated: ["流式输出估算", "Estimated streamed output"], reasoning: ["其中推理 Token", "Reasoning tokens included"],
  target: ["目标输出 Token", "Target output tokens"], prefill: ["输入 / 首字耗时", "Input / time to first token"], e2e: ["端到端吞吐", "End-to-end throughput"],
  control: ["长度控制", "Length control"], fixed: ["定长控制", "Fixed-length controls"], best_effort: ["输出上限 + 达标校验", "Output limit + verification"],
  simulated: ["模拟数据", "Simulated"],
  simulationSpeed: ["模拟速度", "Simulation speed"],
  time: ["测试时间", "Test time"], reason: ["结束原因", "Finish reason"], unknown: ["API 未提供", "Not reported by API"],
  warning: ["本次输出未达到目标，或 API 未提供用量；不会自动加入有效结果对比。", "Output did not match the target, or usage is unavailable. This result is not selected automatically."],
  persistError: ["摘要保存失败；当前结果仍可导出，重启后可能丢失。", "Summary could not be saved. Export it now; it may be lost after restart."],
  comparison: ["历史性能对比", "Historical performance"],
  comparisonHint: ["勾选历史数据加入曲线。同一模型与输出长度分别成组，悬停查看实测值。", "Select history rows to compare. Curves are grouped by model and output length; hover for measurements."],
  metric: ["指标", "Metric"], axis: ["横轴", "X axis"], axisInput: ["输入长度", "Input length"], axisTime: ["测试时间", "Test time"],
  history: ["测试历史", "Test history"], select: ["加入对比", "Compare"], view: ["详情", "Details"], reuse: ["复用配置", "Reuse"],
  selectValid: ["选择已达标", "Select valid"], clear: ["清空选择", "Clear selection"], none: ["暂无历史数据", "No history yet"],
  chartEmpty: ["选择历史记录后显示性能曲线", "Select history records to display performance curves"],
  chartUnavailable: ["图表组件不可用，实测数据仍可在列表中查看或导出。", "Chart component unavailable. Measurements remain available in the table and export."],
  connected: ["实时同步", "Live"], reconnecting: ["正在重连，定时补水中", "Reconnecting; refreshing snapshots"],
  noModels: ["请先配置并启用语言模型", "Configure and enable a language model first"],
  busy: ["正在提交…", "Submitting…"],
  contextError: ["输入与输出之和超过该模型配置的上下文窗口", "Input plus output exceeds the model's configured context window"],
  selected: ["已选", "Selected"], status: ["状态", "Status"],
  measurement: ["生成速度按 API 输出用量计算（含推理），不含首字等待；端到端吞吐包含全部请求时间。", "Generation speed uses API output usage (including reasoning), excluding first-token wait. End-to-end throughput includes the full request."],
};
export const label = (key) => copy[key]?.[getCurrentLanguage().startsWith("zh") ? 0 : 1] ?? key;
