import { getCurrentLanguage } from "../i18n.js?v=20260710-01";

const copy = {
  title: ["吞吐量测试", "Model throughput"],
  subtitle: ["一次测试一个模型、并发数与长度组合，积累结果，比较性能变化。", "Test one model, concurrency and length combination, then compare results over time."],
  scenario: ["测试配置", "Test configuration"], concurrency: ["并发数", "Concurrency"],
  concurrencyHint: ["同一模型同时发起的请求数，支持自定义。", "Number of simultaneous requests; custom values are supported."],
  concurrencyError: ["并发数必须是 1 到 1024 的整数", "Concurrency must be an integer from 1 to 1024"],
  outputError: ["输出 Token 必须是 1 到 1,048,576 的整数", "Output tokens must be an integer from 1 to 1,048,576"],
  model: ["选择模型", "Model"], context: ["上下文 Token", "Context tokens"], output: ["输出 Token", "Output tokens"],
  outputHint: ["设置本次测试的输出上限，详情会记录 API 实际输出量。", "Sets the output limit; details record the actual API output."],
  privacy: ["仅保留最近 50 次性能摘要，不创建用户、会话或线程日志。", "Only the latest 50 performance summaries are retained. No users, sessions or thread logs are created."],
  start: ["开始测试", "Start test"], stop: ["停止测试", "Stop test"], stopping: ["正在停止", "Stopping"],
  refresh: ["刷新", "Refresh"], export: ["导出所选数据", "Export selected"],
  details: ["测试详情", "Test details"], empty: ["选择模型和输出长度，开始第一次测试。", "Select a model and output length to start your first test."],
  current: ["查看当前测试", "View current test"], historical: ["历史结果", "Historical result"],
  running: ["测试中", "Running"], finished: ["已完成", "Completed"], incomplete: ["已记录", "Recorded"], error: ["请求失败", "Request failed"], stopped: ["已停止", "Stopped"], idle: ["等待测试", "Ready"],
  ttft: ["平均首字延迟", "Average time to first token"], ttftMax: ["最慢首字延迟", "Slowest time to first token"],
  decode: ["整体生成速度", "Overall generation speed"], avgDecode: ["单请求平均生成速度", "Average per-request generation speed"],
  prefill: ["整体预填充速度", "Overall prefill speed"], avgPrefill: ["单请求平均预填充速度", "Average per-request prefill speed"],
  elapsed: ["总耗时", "Total duration"],
  actualInput: ["实际输入 Token", "Actual input tokens"], actualOutput: ["实际输出 Token", "Actual output tokens"],
  estimated: ["流式估算（仅供参考）", "Stream estimate (reference only)"], reasoning: ["其中思考 Token", "Reasoning tokens"],
  target: ["输出上限 Token", "Output limit tokens"],
  control: ["长度设置", "Length setting"], fixed: ["模型定长参数", "Model length parameter"], best_effort: ["输出上限", "Output limit"],
  simulated: ["模拟数据", "Simulated"],
  simulationSpeed: ["模拟速度", "Simulation speed"],
  time: ["测试时间", "Test time"], reason: ["结束原因", "Finish reason"], unknown: ["API 未提供", "Not reported by API"],
  persistError: ["摘要保存失败；当前结果仍可导出，重启后可能丢失。", "Summary could not be saved. Export it now; it may be lost after restart."],
  comparison: ["历史性能对比", "Historical performance"],
  comparisonHint: ["勾选历史数据加入曲线。同一模型、并发数与输出长度分别成组，悬停查看实测值。", "Select history rows to compare. Curves are grouped by model, concurrency and output length; hover for measurements."],
  metric: ["指标", "Metric"], axis: ["横轴", "X axis"], axisInput: ["上下文长度", "Context length"], axisTime: ["测试时间", "Test time"],
  history: ["测试历史", "Test history"], select: ["加入对比", "Compare"], view: ["详情", "Details"], reuse: ["复用配置", "Reuse"],
  selectValid: ["选择可比较记录", "Select comparable records"], clear: ["清空选择", "Clear selection"], none: ["暂无历史数据", "No history yet"],
  chartEmpty: ["选择历史记录后显示性能曲线", "Select history records to display performance curves"],
  chartUnavailable: ["图表组件不可用，实测数据仍可在列表中查看或导出。", "Chart component unavailable. Measurements remain available in the table and export."],
  connected: ["实时同步", "Live"], reconnecting: ["正在重连，定时补水中", "Reconnecting; refreshing snapshots"],
  noModels: ["请先配置并启用语言模型", "Configure and enable a language model first"],
  busy: ["正在提交…", "Submitting…"],
  contextError: ["输入与输出之和超过该模型配置的上下文窗口", "Input plus output exceeds the model's configured context window"],
  selected: ["已选", "Selected"], status: ["状态", "Status"],
  measurement: ["整体生成速度只计算首字之后的并发批次生成区间，不含预填充；它按批次墙钟时间计算，所以不一定等于单请求平均速度乘以并发数。预填充速度包含网络等待，首字延迟按并发请求取平均。", "Overall generation speed covers only the concurrent generation interval after the first token, excluding prefill. It uses batch wall time, so it may differ from per-request average speed multiplied by concurrency. Prefill includes network wait, and TTFT is averaged across requests."],
};
export const label = (key) => copy[key]?.[getCurrentLanguage().startsWith("zh") ? 0 : 1] ?? key;
