# -*- coding: utf-8 -*-
# Settings page (general / runtime / LAN / models / prompts / diagnostics / help)
# and files page.

ENTRIES = [
    # ---- settings shell ----
    ("st_title", "系统设置", "System settings"),
    ("st_subtitle", "本地运行时、工作目录和模型配置", "Local runtime, working directory and models"),
    ("st_items", "设置项目", "Settings"),
    ("st_local_note", "桌面端本地设置，保存在本机配置中", "Desktop local settings are stored in this machine's configuration"),
    ("st_tab_general", "通用偏好", "General"),
    ("st_tab_prompts", "提示词包", "Prompt packs"),
    ("st_tab_models", "模型配置", "Models"),
    ("st_tab_runtime", "本地运行时", "Local runtime"),
    ("st_tab_tools", "工具与技能", "Tools & skills"),
    ("st_tab_help", "帮助与关于", "Help & about"),

    # ---- general preferences ----
    ("st_theme", "主题", "Theme"),
    ("st_theme_light", "浅色（蜂巢基调）", "Light (hive tone)"),
    ("st_send_key", "发送键", "Send key"),
    ("st_send_enter", "Enter 发送", "Enter sends"),
    ("st_send_ctrl_enter", "Ctrl+Enter 发送", "Ctrl+Enter sends"),
    ("st_send_enter_newline", "Enter 换行，Ctrl+Enter 发送", "Enter newline, Ctrl+Enter sends"),
    ("st_send_enter_direct", "Enter 直接发送", "Enter sends directly"),
    ("st_save_prefs", "保存偏好", "Save preferences"),

    # ---- runtime ----
    ("st_workspace_root", "工作区根目录", "Workspace root"),
    ("st_workdir", "工作目录", "Working directory"),
    ("st_workdir_note", "更改工作目录后会使用新的文件根目录，原目录的文件不会自动迁移。",
     "Changing the working directory switches to a new file root; files in the previous directory are not migrated."),
    ("st_language", "运行时语言", "Runtime language"),
    ("st_language_hint", "zh-CN 或 en-US", "zh-CN or en-US"),
    ("st_exec_paths", "执行文件路径", "Executable paths"),
    ("st_exec_paths_note", "指定 Python / Git / rg 可执行文件路径，保存后对新启动的工具立即生效；留空表示自动检测。也可将补充包解压到安装目录的 opt/ 下自动识别。",
     "Set Python / Git / rg executable paths; saved paths apply to newly started tools immediately. Empty means auto-detect. Supplement packages unpacked under the install directory's opt/ are also detected."),
    ("st_python_path", "Python 路径", "Python path"),
    ("st_python_hint", "留空自动检测，可指向 python 可执行文件", "Empty auto-detects; may point to a python executable"),
    ("st_git_path", "Git 路径", "Git path"),
    ("st_git_hint", "留空使用系统 PATH 中的 git", "Empty uses git from the system PATH"),
    ("st_rg_path", "rg 路径", "rg path"),
    ("st_rg_hint", "留空自动检测 ripgrep", "Empty auto-detects ripgrep"),

    # ---- LAN ----
    ("st_lan_title", "内网通信", "LAN mesh"),
    ("st_lan_on", "已启用节点发现", "Node discovery enabled"),
    ("st_lan_off", "未启用节点发现", "Node discovery disabled"),
    ("st_lan_node_name", "节点名称", "Node name"),
    ("st_lan_node_name_hint", "本机在内网中的显示名称", "Display name of this machine on the LAN"),
    ("st_lan_node_id", "节点 ID：", "Node ID: "),
    ("st_lan_listen", "监听：", "Listening: "),
    ("st_lan_discovered_prefix", "  ·  已发现 ", "  ·  discovered "),
    ("st_lan_discovered_suffix", " 个节点", " nodes"),
    ("st_lan_empty", "暂无已发现节点", "No discovered nodes"),
    ("st_lan_enable", "启用内网通信", "Enable LAN mesh"),
    ("st_lan_disable", "停用内网通信", "Disable LAN mesh"),

    # ---- models ----
    ("st_models_default_suffix", "  · 默认", "  · default"),
    ("st_current_suffix", "  · 当前", "  · current"),
    ("st_models_loading", "正在加载模型…", "Loading models…"),
    ("st_models_empty", "尚未配置模型", "No models configured"),
    ("st_workdir_colon", "工作目录：", "Working directory: "),
    ("st_pick_model", "选择左侧模型查看配置", "Pick a model on the left to view its settings"),
    ("st_model_colon", "模型：", "Model: "),
    ("st_url_colon", "地址：", "URL: "),
    ("st_is_default", "当前默认", "Current default"),
    ("st_set_default", "设为默认", "Set as default"),
    ("st_models_note", "模型配置保存在本机，修改后在新任务中生效。",
     "Model settings are stored locally and apply to new tasks after changes."),
    ("st_models_count_suffix", " 个模型条目", " model entries"),
    ("st_tools_elsewhere", "工具目录和技能能力已在工具页面统一展示。",
     "The tool catalog and skill capabilities are shown on the tools page."),

    # ---- help / about / diagnostics ----
    ("st_help_native_note", "桌面端使用本地原生运行时，不经本机 HTTP/WebSocket，不拉起 bridge 子进程。",
     "The desktop app runs a local native runtime: no local HTTP/WebSocket hop and no bridge subprocess."),
    ("st_diagnostics", "诊断", "Diagnostics"),
    ("st_export_diagnostics", "导出诊断信息", "Export diagnostics"),
    ("st_diagnostics_note", "导出密钥无关的本机设置与能力计数，便于问题排查。",
     "Exports secret-free local settings and capability counts for troubleshooting."),
    ("st_reset_title", "重置工作状态", "Reset work state"),
    ("st_reset_note", "清理运行状态、队列与临时投影；保留资产、配置、文件与历史。",
     "Clears run state, queues and temporary projections; keeps assets, settings, files and history."),

    # ---- prompt packs ----
    ("pm_readonly_builtin", "内置只读", "Built-in (read-only)"),
    ("pm_custom", "自定义", "Custom"),
    ("pm_builtin_lang_pack", "内置语言包", "Built-in language pack"),
    ("pm_empty", "暂无提示词包", "No prompt packs"),
    ("pm_new", "新建", "New"),
    ("pm_delete_custom", "删除当前自定义包", "Delete the current custom pack"),
    ("pm_segment_edit", "分段编辑", "Segment editor"),
    ("pm_segment_edit_prefix", "分段编辑 · ", "Segment editor · "),
    ("pm_readonly_hint", "只读（内置包）", "Read-only (built-in pack)"),
    ("pm_editable_hint", "可编辑", "Editable"),
    ("pm_segment_role", "角色", "Role"),
    ("pm_segment_engineering", "工程", "Engineering"),
    ("pm_segment_tool_protocol", "工具协议", "Tool protocol"),
    ("pm_segment_skill_protocol", "技能协议", "Skill protocol"),
    ("pm_segment_memory", "记忆", "Memory"),
    ("pm_segment_attach", "附加", "Attachment"),
    ("pm_save_segment", "保存分段", "Save segment"),

    # ---- files page ----
    ("fl_title", "文件工作区", "File workspace"),
    ("fl_container_prefix", "容器 #", "Container #"),
    ("fl_up", "上一级", "Up"),
    ("fl_current_dir", "当前目录", "Current directory"),
    ("fl_workspace_root", "工作区根目录", "Workspace root"),
    ("fl_subdirs", "子目录", "Subdirectories"),
    ("fl_reading", "正在读取…", "Reading…"),
    ("fl_empty", "暂无子目录", "No subdirectories"),
    ("fl_total_prefix", "共 ", "Total "),
    ("fl_total_suffix", " 项 · 文件访问受当前容器根目录限制",
     " items · file access is limited to the current container root"),
    ("fl_switch_dir", "切换目录", "Switch directory"),
    ("fl_search", "搜索当前目录", "Search current directory"),
    ("fl_kind_text", "文本", "Text"),
    ("fl_kind_sheet", "表格", "Sheet"),
    ("fl_kind_deck", "演示", "Slides"),
    ("fl_kind_diagram", "流程图", "Diagram"),
    ("fl_ops", "文件操作", "File actions"),
    ("fl_preview_loading", "正在读取文件…", "Reading file…"),
    ("fl_no_file_selected", "当前目录没有文件", "No file in this directory"),
    ("fl_page_from_prefix", "第 ", "From item "),
    ("fl_page_from_suffix", " 项起", ""),
    ("fl_copy_to", "复制到", "Copy to"),
    ("fl_move_to", "移动到", "Move to"),
    ("fl_open_native", "使用系统程序打开", "Open with system"),
    ("fl_move", "移动", "Move"),
    ("fl_delete_prefix", "将永久删除“", "This permanently deletes “"),
    ("fl_delete_suffix", "”。此操作无法恢复。", "”. This cannot be undone."),
    ("fl_new_name", "新名称", "New name"),
    ("fl_target_path", "目标相对路径", "Target relative path"),
    ("fl_upload", "上传文件", "Upload file"),
    ("fl_download", "下载到本机", "Download to this machine"),
]
