# -*- coding: utf-8 -*-
# Agents page, tools page and dock (chat right pane).

ENTRIES = [
    # ---- agents page ----
    ("ag_title", "专家", "Agents"),
    ("ag_subtitle", "管理可用于新会话的智能体", "Manage agents for new sessions"),
    ("ag_search", "搜索专家", "Search agents"),
    ("ag_new", "新建专家", "New agent"),
    ("ag_tool_count_suffix", " 项工具", " tools"),
    ("ag_available", "可用", "available"),
    ("ag_loading", "正在加载专家…", "Loading agents…"),
    ("ag_empty", "未加载到专家", "No agents loaded"),
    ("ag_editor_title", "专家设置", "Agent settings"),
    ("ag_editor_subtitle", "编辑专家能力和运行策略", "Edit capabilities and run strategy"),
    ("ag_export_card", "导出卡片", "Export card"),
    ("ag_import_card", "导入卡片", "Import card"),
    ("ag_name_label", "专家名称", "Agent name"),
    ("ag_greeting_label", "问候语 / 描述", "Greeting / description"),
    ("ag_greeting_placeholder", "告诉用户这个专家能做什么", "Tell users what this agent can do"),
    ("ag_system_prompt", "系统提示词", "System prompt"),
    ("ag_tool_capability", "工具能力", "Tools"),
    ("ag_tools_available_suffix", " 项可用", " available"),
    ("ag_search_tools", "搜索工具", "Search tools"),
    ("ag_run_strategy", "运行策略", "Run strategy"),
    ("ag_model_key", "模型配置键", "Model config key"),
    ("ag_model_key_hint", "留空继承默认", "Empty inherits the default"),
    ("ag_workdir_container", "工作目录容器", "Working directory container"),
    ("ag_container_prefix", "容器 #", "Container #"),
    ("ag_permission_mode", "权限模式", "Permission mode"),
    ("ag_prefer_mother", "偏好母智能体", "Prefer mother agent"),
    ("ag_switch_on", "已开启", "On"),
    ("ag_switch_off", "已关闭", "Off"),
    ("ag_preset_questions", "预设问题", "Preset questions"),
    ("ag_save_settings", "保存设置", "Save settings"),
    ("ag_delete_confirm_title", "确认删除智能体", "Delete this agent"),
    ("ag_delete_prefix", "将删除“", "This permanently deletes “"),
    ("ag_delete_suffix", "”及其本地配置。已有会话不会被改写。",
     "” and its local configuration. Existing conversations are not rewritten."),
    ("ag_import_title", "导入工蜂卡", "Import worker card"),
    ("ag_import_hint", "卡片目录：工作区 agent-cards 目录下的导出文件",
     "Card directory: exported files under the workspace agent-cards directory"),
    ("ag_overwrite_label", "覆盖同名专家（导入前需确认）", "Overwrite agents with the same name (confirm before import)"),
    ("ag_import_button", "导入", "Import"),
    ("ag_cards_scanning", "正在扫描卡片目录…", "Scanning card directory…"),
    ("ag_cards_empty", "卡片目录暂无可导入的工蜂卡文件", "No importable worker cards in the card directory"),
    ("ag_preview_skill", "预览技能", "Skill preview"),
    ("ag_silent_run", "静默运行", "Silent run"),

    # ---- tools page ----
    ("tl_title", "工具", "Tools"),
    ("tl_subtitle", "当前账户可使用的内置工具、技能和连接能力",
     "Built-in tools, skills and connections for the current account"),
    ("tl_category", "工具分类", "Category"),
    ("tl_cat_all", "全部工具", "All tools"),
    ("tl_cat_builtin", "内置工具", "Built-in tools"),
    ("tl_cat_mcp", "MCP 工具", "MCP tools"),
    ("tl_cat_skills", "技能", "Skills"),
    ("tl_cat_kb", "知识库", "Knowledge base"),
    ("tl_cat_user", "用户工具", "User tools"),
    ("tl_cat_shared", "共享工具", "Shared tools"),
    ("tl_cat_a2a", "A2A 工具", "A2A tools"),
    ("tl_count_suffix", " 项能力 · 工具权限由本地运行时统一管理",
     " capabilities · tool permissions are managed by the local runtime"),
    ("tl_enabled_capabilities", "已启用的运行时能力", "Enabled runtime capabilities"),
    ("tl_loading", "正在加载工具…", "Loading tools…"),
    ("tl_empty", "未加载到可用工具", "No tools loaded"),

    # ---- dock (chat right pane) ----
    ("dk_title", "本地工作目录", "Local working directory"),
    ("dk_threads_title", "工作线程", "Threads"),
    ("dk_thread_ops", "线程操作", "Thread actions"),
    ("dk_details", "详情", "Details"),
    ("dk_archive", "归档", "Archive"),
    ("dk_workdir", "工作目录", "Working directory"),
    ("dk_switch_dir", "切换目录", "Switch directory"),
    ("dk_new_file", "新建文件", "New file"),
    ("dk_new_text", "文本 .txt", "Text .txt"),
    ("dk_new_sheet", "表格 .xlsx", "Sheet .xlsx"),
    ("dk_new_deck", "演示文稿 .pptx", "Slides .pptx"),
    ("dk_new_diagram", "流程图 .drawio", "Diagram .drawio"),
    ("dk_open", "打开", "Open"),
    ("dk_copy_path", "复制路径", "Copy path"),
    ("dk_open_native", "系统打开", "Open with system"),
    ("dk_reading", "正在读取…", "Reading…"),
]
