# -*- coding: utf-8 -*-
# Expert data / expert preview / agent editor literals.

ENTRIES = [
    # expert_data.slint
    ("ed_total_legend", "○ 累计消耗", "○ Total usage"),
    ("ed_all_tags", "全部标签", "All tags"),
    ("ed_memory_desc", "将可复用的长期事实整理为模型友好的记忆索引与详情。", "Organize reusable long-term facts into model-friendly memory indexes."),
    ("ed_replicate_desc", "将当前智能体的记忆复制到目标智能体，覆盖目标已有记忆。", "Copy this agent's memories to a target agent, overwriting existing ones."),
    ("ed_tool_calls", "工具调用次数", "Tool call count"),
    ("ed_tool_heatmap", "工具调用热力图", "Tool call heatmap"),
    ("ed_archived_threads", "已归档线程", "Archived threads"),
    ("ed_heatmap_hint", "按工具统计调用次数，颜色越偏红表示调用越频繁", "Calls per tool; the redder the color, the more frequent"),
    ("ed_search_memory", "搜索记忆 ID、索引标题或内容详情", "Search memory ID, index title or detail"),
    ("ed_new_memory", "新建碎片", "New memory"),
    ("ed_daily_trend", "日运行趋势", "Daily trend"),
    ("ed_no_memories", "暂无记忆碎片", "No memories"),
    ("ed_view_archive", "查看归档内容", "View archived content"),
    ("ed_tag", "标签", "Tags"),
    ("ed_delete_confirm", "确定删除此记忆碎片？", "Delete this memory?"),
    ("ed_confirm_overwrite", "确认覆盖", "Confirm overwrite"),
    ("ed_index_title", "索引标题", "Index title"),
    ("ed_total_usage", "累计消耗", "Total usage"),
    ("ed_edit_memory", "编辑记忆碎片", "Edit memory"),
    ("ed_replicate", "记忆复刻", "Memory replication"),
    ("ed_duration", "运行时长", "Run duration"),
    ("ed_trend_hint", "默认显示累计消耗，点击趋势图中的某一天可切换工具调用热力图日期", "Shows total usage by default; click a day to switch the heatmap date"),
    # expert_preview.slint
    ("epv_yield", "会话让出", "Session yield"),
    ("epv_greet_long", "你好，我可以帮助你整理资料、分析数据和完成日常任务。", "Hi, I can help organize materials, analyze data and handle daily tasks."),
    ("epv_greet_short", "你好，我可以帮助你整理资料。", "Hi, I can help organize materials."),
    ("epv_system_sample", "你是一个乐于助人的智能体～", "You are a helpful agent."),
    ("epv_style_sample", "使用简洁的回复风格。", "Reply in a concise style."),
    ("epv_info", "信息", "Info"),
    ("epv_edit_doc_desc", "修改已有文档的指定内容。", "Edit specific parts of an existing document."),
    ("epv_cron_desc", "创建和管理定时任务。", "Create and manage scheduled tasks."),
    ("epv_create_doc_desc", "创建文档并保存到工作目录。", "Create documents and save them to the work folder."),
    ("epv_export_doc_desc", "将结果导出为可阅读文档。", "Export results as a readable document."),
    ("epv_manual_write", "手动写入", "Manual write"),
    ("epv_summarize_doc", "整理文档要点", "Summarize documents"),
    ("epv_doc_gen", "文档生成", "Document generation"),
    ("epv_doc_edit", "文档编辑", "Document editing"),
    ("epv_new_session", "新会话", "New session"),
    ("epv_final_reply", "最终回复", "Final reply"),
    ("epv_search_desc", "检索可用资料与内容索引。", "Search available materials and content indexes."),
    ("epv_summarize_todos", "汇总待办事项", "Summarize to-dos"),
    ("epv_channel_ok", "渠道连接正常", "Channel connected"),
    ("epv_sample_prompt", "示例提示词", "Sample prompt"),
    ("epv_sample_channel", "示例渠道", "Sample channel"),
    ("epv_sample_memory", "示例记忆", "Sample memory"),
    ("epv_sample_greeting", "示例问候语", "Sample greeting"),
    ("epv_export_result", "结果导出", "Result export"),
    ("epv_yield_desc", "让出当前回合控制权，并可附带一条简短说明。", "Yield the current turn, optionally with a short note."),
    ("epv_memory_mgmt", "记忆管理", "Memory management"),
    ("epv_knowledge_search", "资料检索", "Knowledge search"),
    ("epv_final_reply_desc", "返回给用户的最终回复，包含文件和报告等产出。", "The final reply to the user, including files and reports."),
    ("epv_memory_mgmt_desc", "管理当前智能体的长期记忆。", "Manage this agent's long-term memory."),
    ("epv_default_hive", "默认蜂群", "Default hive"),
    # expert_widgets.slint
    ("ew_select_all", "全选", "Select all"),
    ("ew_deselect_all", "取消全选", "Deselect all"),
    ("ew_type_label", "类型：", "Type: "),
    # agents_page.slint
    ("ap_all_hives", "全部蜂群", "All hives"),
    ("ap_archive_thread", "归档线程", "Archive thread"),
    ("ap_agent_settings", "智能体设置", "Agent settings"),
    ("ap_memories", "记忆碎片", "Memories"),
    ("ap_back_chat", "返回对话", "Back to chat"),
    # agents_editor.slint
    ("ae_prefer_mother", "优先母蜂", "Prefer primary hive"),
    ("ae_name_placeholder", "例如：产品分析助手", "e.g. Analysis assistant"),
    ("ae_workdir_1", "工作目录 1", "Workspace 1"),
    ("ae_workdir_2", "工作目录 2", "Workspace 2"),
    ("ae_workdir_3", "工作目录 3", "Workspace 3"),
    ("ae_workdir_4", "工作目录 4", "Workspace 4"),
    ("ae_workdir_5", "工作目录 5", "Workspace 5"),
    ("ae_workdir_6", "工作目录 6", "Workspace 6"),
    ("ae_workdir_7", "工作目录 7", "Workspace 7"),
    ("ae_workdir_8", "工作目录 8", "Workspace 8"),
    ("ae_workdir_9", "工作目录 9", "Workspace 9"),
    ("ae_workdir_10", "工作目录 10", "Workspace 10"),
    ("ae_prefer_mother_hint", "开启后，当蜂群未显式指定母蜂时，默认优先使用该智能体。", "When the hive does not name a primary agent, prefer this one."),
    ("ae_preview_skill_hint", "开启后，挂载技能会将 SKILL.md 直接并入系统提示词。", "Mounted skills merge SKILL.md straight into the system prompt."),
    ("ae_silent_hint", "开启后，该智能体不会出现在消息中栏和蜂群右侧消息栏中。", "This agent stays out of the message lists when enabled."),
    ("ae_add_question", "添加预设问题", "Add preset question"),
    ("ae_agent_name", "智能体名称", "Agent name"),
    ("ae_greeting_hint", "用于会话中的首次问候", "Used for the first greeting in a session"),
    ("ae_model_hint", "留空时使用默认模型。", "Falls back to the default model when empty."),
    ("ae_workdir_hint", "相同工作目录编号（1-10）的智能体会共享同一文件区。", "Agents sharing a workspace number (1-10) share one file area."),
    ("ae_hive_group", "蜂群分组", "Hive group"),
    ("ae_extra_prompt_hint", "输入需要追加到基础系统提示词后的内容", "Text appended after the base system prompt"),
    ("ae_greeting", "问候语", "Greeting"),
    ("ae_silent", "静默模式", "Silent mode"),
    ("ae_preview_skill", "预习技能", "Inline skill"),
    ("ae_extra_prompt", "额外提示词", "Extra prompt"),
]
