# -*- coding: utf-8 -*-
# Rust-side UI strings: status bar, dialogs, tray, demo harness feedback.
# Templates use {0}..{n}; call sites pre-format arguments.
# err_op_* values are argument phrases (never rendered alone).

ENTRIES = [
    # ---- generic error templates ----
    ("err_cannot", "无法{0}：{1}", "Unable to {0}: {1}"),
    ("err_failed", "{0}失败：{1}", "{0} failed: {1}"),
    ("st_error_prefix", "错误：{0}", "Error: {0}"),
    ("st_tray_unavailable", "系统托盘不可用：{0}", "System tray unavailable: {0}"),

    # ---- operations for err_cannot (zh phrase, en verb phrase) ----
    ("err_op_open_native", "使用系统程序打开", "open with the system"),
    ("err_op_save_file", "保存文件", "save the file"),
    ("err_op_stop", "停止", "stop generation"),
    ("err_op_switch_workdir", "切换工作目录", "switch the working directory"),
    ("err_op_create_file", "创建文件", "create the file"),
    ("err_op_create_dir", "创建目录", "create the directory"),
    ("err_op_create_group", "创建群组", "create the group"),
    ("err_op_delete_cron", "删除定时任务", "delete the scheduled task"),
    ("err_op_delete_channel", "删除渠道账号", "delete the channel account"),
    ("err_op_delete_binding", "删除绑定", "delete the binding"),
    ("err_op_load_session", "加载会话", "load the session"),
    ("err_op_load_earlier", "加载更早消息", "load earlier messages"),
    ("err_op_load_group_messages", "加载群组消息", "load group messages"),
    ("err_op_send", "发送", "send"),
    ("err_op_start_runtime", "启动内嵌运行时", "start the embedded runtime"),
    ("err_op_archive_thread", "归档工作线程", "archive the thread"),
    ("err_op_restore_session", "恢复会话", "restore the session"),
    ("err_op_open_direct_chat", "打开单聊", "open the direct chat"),
    ("err_op_new_session", "新建会话", "create the session"),
    ("err_op_update_cron", "更新定时任务", "update the scheduled task"),
    ("err_op_update_channel", "更新渠道账号", "update the channel account"),
    ("err_op_minimize_tray", "最小化到系统托盘", "minimize to tray"),
    ("err_op_run_now", "立即运行任务", "run the task now"),
    ("err_op_read_session", "读取会话", "read the session"),
    ("err_op_read_cron", "读取定时任务", "read scheduled tasks"),
    ("err_op_read_plaza", "读取广场资产", "read plaza assets"),
    ("err_op_read_agents", "读取智能体列表", "read the agent list"),
    ("err_op_read_channels", "读取渠道账号", "read channel accounts"),
    ("err_op_read_world", "读取用户世界", "read the user world"),
    ("err_op_read_thread_log", "读取线程日志", "read the thread log"),
    ("err_op_read_bindings", "读取绑定", "read bindings"),
    ("err_op_read_announcement", "读取群公告", "read the group announcement"),
    ("err_op_read_contacts", "读取联系人", "read contacts"),
    ("err_op_read_logs", "读取运行日志", "read run logs"),
    ("err_op_read_runs", "读取运行记录", "read run records"),
    ("err_op_rename_thread", "重命名工作线程", "rename the thread"),

    # ---- operations for err_failed ----
    ("fail_op_save_cron", "保存定时任务", "Save scheduled task"),
    ("fail_op_save_channel", "保存渠道账号", "Save channel account"),
    ("fail_op_save_announcement", "公告保存", "Save announcement"),
    ("fail_op_realtime_subscribe", "实时消息订阅", "Realtime subscription"),
    ("fail_op_import", "导入", "Import"),
    ("fail_op_send_message", "发送消息", "Send message"),
    ("fail_op_file_action", "文件操作", "File action"),
    ("fail_op_asr", "语音识别", "Voice recognition"),
    ("fail_op_reconnect", "重连", "Reconnect"),

    # ---- validation and progress ----
    ("st_cron_expr_empty", "Cron 表达式不能为空", "Cron expression cannot be empty"),
    ("st_task_name_empty", "任务名称不能为空", "Task name cannot be empty"),
    ("st_task_running", "任务正在运行中，未重复排队", "Task already running; not queued again"),
    ("st_name_invalid", "名称不能为空且不能超过 80 个字符", "Name cannot be empty and must be at most 80 characters"),
    ("st_agent_name_invalid", "智能体名称不能为空且不能超过 80 个字符", "Agent name cannot be empty and must be at most 80 characters"),
    ("st_exec_interval_range", "执行间隔必须在 1..86400 秒之间", "Interval must be between 1 and 86400 seconds"),
    ("st_exec_message_empty", "执行消息不能为空", "Message cannot be empty"),
    ("st_channel_type_required", "请选择渠道类型", "Pick a channel type"),
    ("st_members_required", "请至少选择 1 名初始成员", "Pick at least 1 initial member"),
    ("st_runtime_form_invalid", "请填写工作目录和有效的运行时语言", "Fill in the working directory and a valid runtime language"),
    ("st_model_form_invalid", "请填写模型配置，并选择有效的模型类型", "Fill in the model settings and pick a valid model type"),
    ("st_no_session", "请先创建或选择一个会话", "Create or select a session first"),
    ("st_no_asr_model", "请先在系统设置中配置默认语音识别模型", "Configure a default ASR model in system settings first"),
    ("st_input_too_long", "输入过长，请分段发送", "Input too long; send in parts"),
    ("st_demo_input_too_long", "演示输入过长，请缩短后重试", "Demo input too long; shorten and retry"),
    ("st_syncing", "正在同步…", "Syncing…"),
    ("st_probing_context", "正在探测上下文…", "Probing context…"),
    ("st_probing_voices", "正在探测语音列表…", "Probing voice list…"),
    ("st_transcribing", "正在识别录音…", "Transcribing recording…"),
    ("st_recording_hint", "正在录音，再次点击停止", "Recording; click again to stop"),
    ("st_stopping", "正在停止…", "Stopping…"),
    ("st_runtime_loading", "正在加载内嵌运行时…", "Loading embedded runtime…"),
    ("st_runtime_starting", "正在启动内嵌运行时…", "Starting embedded runtime…"),
    ("st_runtime_ready", "内嵌运行时已就绪", "Embedded runtime ready"),

    # ---- success feedback ----
    ("st_prefs_saved", "偏好已保存", "Preferences saved"),
    ("st_profile_saved", "个人资料已保存", "Profile saved"),
    ("st_announcement_saved", "公告已更新", "Announcement updated"),
    ("st_lan_saved", "内网通信设置已保存", "LAN mesh settings saved"),
    ("st_cron_saved", "定时任务已保存", "Scheduled task saved"),
    ("st_cron_deleted", "定时任务已删除", "Scheduled task deleted"),
    ("st_workdir_switched", "工作目录已切换", "Working directory switched"),
    ("st_thread_archived", "工作线程已归档", "Thread archived"),
    ("st_thread_renamed", "工作线程已重命名", "Thread renamed"),
    ("st_tools_synced", "工具目录已同步", "Tool catalog synced"),
    ("st_queued_run_now", "已加入立即执行队列", "Queued for immediate run"),
    ("st_card_exported_path", "工蜂卡已导出：{0}", "Worker card exported: {0}"),
    ("st_imported_named", "已导入「{0}」：{1}", "Imported “{0}”: {1}"),
    ("st_imported", "已导入：{0}", "Imported: {0}"),
    ("st_reconnect_requested", "已请求重连，稍后查看运行日志确认", "Reconnect requested; check run logs shortly"),
    ("st_prompt_segment_saved", "提示词分段已保存", "Prompt segment saved"),
    ("st_prompt_pack_created", "提示词包已创建：{0}", "Prompt pack created: {0}"),
    ("st_prompt_pack_deleted", "提示词包已删除", "Prompt pack deleted"),
    ("st_file_saved", "文件已保存", "File saved"),
    ("st_file_created", "文件已创建", "File created"),
    ("st_file_ops_done", "文件操作已完成", "File action completed"),
    ("st_agent_created", "新智能体已创建", "New agent created"),
    ("st_agents_synced", "智能体列表已同步", "Agent list synced"),
    ("st_agent_deleted", "智能体已删除", "Agent deleted"),
    ("st_agent_saved", "智能体配置已保存", "Agent settings saved"),
    ("st_local_settings_synced", "本地设置已同步", "Local settings synced"),
    ("st_model_saved", "模型配置已保存到本地运行时", "Model settings saved to the local runtime"),
    ("st_default_model_updated", "默认模型已更新", "Default model updated"),
    ("st_channel_saved", "渠道账号已保存", "Channel account saved"),
    ("st_channel_deleted", "渠道账号已删除", "Channel account deleted"),
    ("st_binding_deleted", "绑定已删除", "Binding deleted"),
    ("st_group_created", "群组已创建", "Group created"),
    ("st_runtime_saved", "运行时设置已保存", "Runtime settings saved"),
    ("st_dir_created", "目录已创建", "Directory created"),
    ("st_voices_found", "语音列表探测成功：{0} 项", "Voice list probe succeeded: {0} items"),
    ("st_diagnostics_exported", "诊断信息已导出：{0}", "Diagnostics exported: {0}"),
    ("st_attachment_added", "{0}已放入输入区，发送即可交给模型", "{0} added to the composer; send to hand it to the model"),
    ("st_max_attachments", "最多可附加 {0} 张截图，请先移除一张", "You can attach up to {0} screenshots; remove one first"),
    ("st_voice_transcribed", "语音已转写到输入区，可编辑后发送", "Voice transcribed into the composer; edit and send"),
    ("st_minimized_tray", "已最小化到系统托盘；点击托盘图标可恢复窗口", "Minimized to the tray; click the tray icon to restore the window"),
    ("st_no_voices", "提供方未返回语音列表", "Provider returned no voice list"),

    # ---- dialog texts ----
    ("dlg_probe_context", "上下文探测", "Context probe"),
    ("dlg_probe_voices", "语音列表探测", "Voice list probe"),
    ("dlg_save_failed", "保存失败", "Save failed"),
    ("dlg_operation_failed", "操作失败", "Operation failed"),
    ("dlg_overwrite_confirm", "将用卡片内容覆盖同名专家的名称、提示词、工具与运行策略，且不可自动恢复。确认继续？",
     "The card will overwrite the same-name agent's name, prompt, tools and run strategy; this cannot be undone automatically. Continue?"),
    ("dlg_work_state_reset", "工作状态已重置", "Work state reset"),
    ("dlg_card_exported", "工蜂卡已导出", "Worker card exported"),
    ("dlg_written", "已写入 {0}", "Written to {0}"),
    ("dlg_written_import_hint", "已写入 {0}；导入时从同一目录选择。", "Written to {0}; pick the same directory when importing."),
    ("dlg_no_voices", "提供方未返回语音列表。", "Provider returned no voice list."),
    ("dlg_diagnostics_exported", "诊断信息已导出", "Diagnostics exported"),
    ("dlg_overwrite_import_title", "确认覆盖导入", "Confirm overwrite import"),
    ("dlg_thread_log", "线程日志", "Thread log"),
    ("dlg_check_model", "请检查模型配置后重试。", "Check the model settings and retry."),
    ("dlg_config_save_failed", "配置保存失败，请检查目录权限后重试", "Failed to save settings; check directory permissions and retry."),
    ("st_thread_log_title", "线程日志 · {0}", "Thread log · {0}"),

    # ---- demo harness ----
    ("demo_time_now", "现在", "Just now"),
    ("st_demo_task_reset", "已重置当前演示任务", "Demo task reset"),
    ("st_demo_not_sent", "本地演示 · 消息未发送至后端", "Local demo · message not sent to backend"),
    ("st_demo_agent_created", "智能体已创建 · 仅本次演示有效", "Agent created (demo only)"),
    ("st_demo_model_saved", "模型已保存 · 仅本次演示有效", "Model saved (demo only)"),
    ("st_demo_settings_saved", "设置已保存 · 仅本次演示有效", "Settings saved (demo only)"),
    ("st_demo_config_saved", "配置已保存 · 仅本次演示有效", "Configuration saved (demo only)"),
    ("st_demo_default_model_updated", "默认模型已更新 · 仅本次演示有效", "Default model updated (demo only)"),
    ("shot_kind_region", "截图", "Screenshot"),
    ("shot_kind_fullscreen", "全屏截图", "Fullscreen screenshot"),
]
