ENTRIES = [
    ('tm_admin', '管理员开放工具', 'Administrator tools'),
    ('tm_admin_desc', '查看管理员开放的内置工具、MCP 工具、技能工具与知识库工具', 'View available built-in, MCP, skill and knowledge tools'),
    ('tm_custom', '自建工具', 'Custom tools'),
    ('tm_mcp_desc', '连接和管理 MCP 工具', 'Connect and manage MCP tools'),
    ('tm_skills', '技能工具', 'Skill tools'),
    ('tm_skills_desc', '上传与编辑技能包', 'Upload and edit skill packages'),
    ('tm_knowledge', '知识库工具', 'Knowledge tools'),
    ('tm_knowledge_desc', '管理知识库及检索文件', 'Manage knowledge bases and files'),
    ('tm_none', '暂无', 'None'),
    ('tm_mcp_tip', '可连接 MCP 服务并管理工具', 'Connect MCP services and manage tools'),
    ('tm_servers', 'MCP 服务器', 'MCP servers'),
    ('tm_no_servers', '暂无 MCP 服务器', 'No MCP servers'),
    ('tm_no_detail', '暂无详情', 'No details'),
    ('tm_connect', '连接', 'Connect'),
    ('tm_mcp_tools_tip', '连接后可查看工具列表，并按需启用', 'Connect to view available tools'),
    ('tm_select_tool', '选择工具', 'Select a tool'),
    ('tm_skill_tip', '从技能目录读取可用技能，并支持直接编辑文件。上传支持常见压缩包格式，部分格式依赖本机解压器。', 'Read skills from their directories and edit files. Archive support depends on the local extractor.'),
    ('tm_skill_list', '技能列表', 'Skills'),
    ('tm_no_skills', '暂无技能', 'No skills'),
    ('tm_global', '全局', 'Global'),
    ('tm_local', '自定义', 'Custom'),
    ('tm_select_skill', '未选择技能', 'No skill selected'),
    ('tm_search_files', '搜索文件', 'Search files'),
    ('tm_folder', '文件夹', 'Folder'),
    ('tm_kb_tip', '在此创建与管理你的知识库', 'Create and manage your knowledge bases'),
    ('tm_kb_list', '知识库列表', 'Knowledge bases'),
    ('tm_no_kb', '暂无知识库', 'No knowledge bases'),
    ('tm_select_kb', '未选择知识库', 'No knowledge base selected'),
    ('tm_select_file', '未选择文件', 'No file selected'),
    ('tm_files', '文件列表', 'Files'),
    ('tm_save', '保存', 'Save'),
    ('tm_edit', '编辑', 'Edit'),
    ('tm_add', '新建', 'Create'),
    ('tm_import', '导入', 'Import'),
    ('tm_export', '导出', 'Export'),
    ('tm_upload', '上传文件', 'Upload file'),
    ('tm_name', '名称', 'Name'),
    ('tm_value', '地址 / 描述 / 文件路径', 'Endpoint / description / file path'),
    ('tm_confirm_delete', '确认删除选中项及其本地内容？', 'Delete the selected item and its local contents?'),
    ('tm_readonly', '全局技能只读', 'Global skills are read-only'),
    ('tm_path', '文件路径', 'File path'),
    ('tm_more', '加载更多', 'Load more'),
    ('tm_close', '关闭', 'Close'),
    ('tm_mcp_add_title', '新增 MCP 服务器', 'Add MCP server'),
    ('tm_mcp_edit_title', '编辑 MCP 服务器', 'Edit MCP server'),
    ('tm_display_name', '显示名称', 'Display name'),
    ('tm_display_name_ph', '用于显示的名称', 'Name used for display'),
    ('tm_unique_name_ph', '唯一名称', 'Unique name'),
    ('tm_endpoint', '地址', 'Endpoint'),
    ('tm_transport', '传输方式', 'Transport'),
    ('tm_desc', '描述', 'Description'),
    ('tm_desc_ph', '请输入描述', 'Enter a description'),
    ('tm_headers', '请求头', 'Headers'),
    ('tm_headers_error', '请求头必须是 JSON 对象', 'Headers must be a JSON object'),
    ('tm_struct_preview', '结构预览', 'Structure preview'),
    ('tm_struct_ph', '填写名称与地址后生成结构预览', 'Enter a name and endpoint to preview the structure'),
    ('tm_kb_add_title', '新增知识库', 'Add knowledge base'),
    ('tm_kb_edit_title', '编辑知识库', 'Edit knowledge base'),
    ('tm_kb_name_ph', '请输入名称', 'Enter a name'),
    ('tm_name_required', '请输入名称', 'Name is required'),
    ('tm_type', '类型', 'Type'),
    ('tm_type_vector', '向量知识库', 'Vector knowledge base'),
    ('tm_type_literal', '字面知识库', 'Literal knowledge base'),
    ('tm_type_ragflow', 'RAGFlow 知识库', 'RAGFlow knowledge base'),
    ('tm_advanced', '高级选项', 'Advanced options'),
    ('tm_embedding_model', '嵌入模型', 'Embedding model'),
    ('tm_embedding_ph', '留空使用默认配置', 'Empty uses the default'),
    ('tm_chunk_size', '切块大小', 'Chunk size'),
    ('tm_chunk_overlap', '切块重叠', 'Chunk overlap'),
    ('tm_kb_vector_tip', '向量知识库路径由系统自动管理', 'Vector knowledge base paths are managed automatically'),
    ('tm_kb_ragflow_tip', 'RAGFlow 知识库使用远端 Dataset，保存后自动创建并绑定。', 'RAGFlow knowledge bases use a remote dataset, created and bound on save.'),
    ('tm_kb_literal_tip', '字面知识库可直接编辑目录中的文本文件', 'Literal knowledge bases edit text files in their directory'),
    ('tm_dataset_id', '已有 Dataset ID', 'Existing dataset ID'),
    ('tm_dataset_ph', '留空则自动创建 Dataset', 'Empty creates a dataset automatically'),
    ('tm_chunk_size_ph', '例如 500', 'e.g. 500'),
    ('tm_chunk_overlap_ph', '例如 50', 'e.g. 50'),
    ('tm_new_file', '新建文件', 'New file'),
    ('tm_import_pick', '选择技能压缩包', 'Select a skill archive'),
    ('tm_importing', '正在导入技能包…', 'Importing skill archive…'),
]
