# -*- coding: utf-8 -*-
# Settings page (general / runtime / LAN / models / prompts / diagnostics / help)
# and files page.

ENTRIES = [
    # ---- settings shell ----
    ("st_title", "系统设置", "System settings"),
    ("st_subtitle", "本地运行时、工作目录和模型配置", "Local runtime, working directory and models"),
    ("st_items", "设置项目", "Settings"),
    ("st_local_note", "桌面端本地设置，保存在本机配置中", "Desktop local settings are stored in this machine's configuration"),
    ("st_tab_general", "通用偏好", "General"),
    ("st_tab_prompts", "提示词包", "Prompt packs"),
    ("st_tab_models", "模型配置", "Models"),
    ("st_tab_runtime", "本地运行时", "Local runtime"),
    ("st_tab_tools", "工具与技能", "Tools & skills"),
    ("st_tab_help", "帮助与关于", "Help & about"),

    # ---- twelve-category navigation (§9.2) ----
    ("stc_back", "返回应用", "Back to app"),
    ("stc_search", "搜索设置", "Search settings"),
    ("stc_none_title", "没有匹配的设置分类", "No matching category"),
    ("stc_none_note", "换个关键词，或清空搜索查看全部分类。", "Try another keyword, or clear the search to see every category."),
    ("stc_general", "常规", "General"),
    ("stc_general_note", "发送、外观、运行环境与诊断", "Sending, appearance, runtime and diagnostics"),
    ("stc_models", "模型设置", "Models"),
    ("stc_models_note", "模型清单、默认模型与参数", "Model list, default model and parameters"),
    ("stc_tools", "工具管理", "Tools"),
    ("stc_tools_note", "内置工具、MCP、知识库与资源", "Built-in tools, MCP, knowledge bases and resources"),
    ("stc_agent", "智能体设置", "Agent"),
    ("stc_agent_note", "内置智能体的提示词与行为", "Built-in agent prompt and behaviour"),
    ("stc_pet", "桌宠", "Companion"),
    ("stc_pet_note", "形象库、显示方式与动画联动", "Library, display mode and animation"),
    ("stc_cron", "定时任务", "Scheduled tasks"),
    ("stc_cron_note", "按计划触发的任务与运行记录", "Scheduled jobs and their runs"),
    ("stc_memory", "记忆碎片", "Memories"),
    ("stc_memory_note", "长期记忆条目，可增删改", "Long-term memory entries"),
    ("stc_channels", "渠道设置", "Channels"),
    ("stc_channels_note", "渠道账号、绑定与日志", "Channel accounts, bindings and logs"),
    ("stc_runs", "运行记录", "Activity"),
    ("stc_runs_note", "用量统计与线程日志", "Usage statistics and thread logs"),
    ("stc_prompts", "提示词包", "Prompt packs"),
    ("stc_prompts_note", "分段编辑与最终提示词预览", "Segment editing and final prompt preview"),
    ("stc_archives", "归档线程", "Archived threads"),
    ("stc_archives_note", "已归档线程，可查看或彻底删除", "Archived threads: review or delete"),
    ("stc_help", "帮助", "Help"),
    ("stc_help_note", "快捷键、关于与诊断导出", "Shortcuts, about and diagnostics"),
    ("stc_local_note", "以下内容都是本机设置，保存在本地配置中，不上传。", "Everything here is local to this machine and is never uploaded."),
    ("stc_pet_tab", "形象库", "Library"),
    ("stc_pet_stage", "动态形象", "Animation"),
    ("stc_pet_note_short", "桌宠的显示、缩放与位置由桌宠窗口控制，此处管理形象库。", "The companion window owns visibility, scale and position; this manages the library."),
    ("stc_runs_flow", "线程日志", "Thread log"),
    ("stc_archives_empty", "还没有归档线程。", "No archived threads yet."),
    ("stc_runs_tab", "用量统计", "Usage"),
    ("stc_archives_open", "查看", "Open"),
    ("stc_agent_name", "智能体名称", "Agent name"),
    ("stc_agent_greeting", "问候语", "Greeting"),
    ("stc_agent_greeting_hint", "用于会话中的首次问候", "Used for the first greeting in a session"),
    ("stc_agent_extra_prompt", "额外提示词", "Extra prompt"),
    ("stc_agent_extra_prompt_hint", "输入需要追加到基础系统提示词后的内容",
     "Text appended after the base system prompt"),
    ("stc_agent_admin_tools", "管理员开放工具", "Administrator-enabled tools"),
    ("stc_agent_behavior", "行为开关", "Behaviour"),
    ("stc_agent_behavior_note", "这些开关作用于内置智能体的每一次运行。", "These switches apply to every run of the built-in agent."),
    ("stc_agent_model_hint", "只能选择「模型设置」中已配置的对话模型；未配置时请先到模型设置添加。",
     "Only conversational models configured in Models can be used; add one there first if the list is empty."),
    ("stc_agent_tools_note", "勾选随「保存」一起写入内置智能体的工具启用集合；搜索只过滤当前列表。",
     "Checks join the built-in agent's enabled tool set on save; the box only filters this list."),
    ("stc_agent_tool_no_desc", "无说明", "No description"),
    ("stc_agent_questions_note", "最多 12 条，随配置保存；回车或点「+」加入。",
     "At most 12 entries, saved with the configuration; press Enter or “+” to add."),
    ("stc_agent_question_add", "添加预设问题", "Add preset question"),
    ("stc_agent_question_placeholder", "输入一条预设问题…", "Type a preset question…"),
    ("stc_agent_preview_skill_note", "运行前先预览将要调用的技能内容。", "Preview the skill content a run is about to use."),
    ("stc_agent_silent_note", "不向用户播报中间步骤，只输出最终结果。", "Skip intermediate narration and emit only the final result."),
    ("stc_agent_prefer_mother_note", "优先选择母智能体承担子任务。", "Prefer the mother agent when delegating subtasks."),
    ("stc_agent_run", "运行策略", "Run strategy"),
    ("stc_agent_run_note", "权限模式由输入区的选择器统一控制。", "The composer's selector owns the permission mode."),
    ("stc_runs_duration", "累计运行", "Total runtime"),
    ("stc_runs_tokens", "累计令牌", "Total tokens"),
    ("stc_runs_calls", "工具调用", "Tool calls"),
    ("stc_runs_heat", "活跃度", "Activity"),
    ("stc_runs_heat_note", "按最近统计窗口汇总。", "Summarised over the most recent window."),
    ("stc_runs_empty", "还没有统计数据。", "No statistics yet."),
    ("stc_runs_open", "打开线程日志", "Open thread log"),
    ("stc_runs_export", "导出日志", "Export log"),
    ("stc_runs_flow_note", "完整事件流，可筛选、分页与导出。", "The full event stream: filter, page and export."),
    ("pet_show", "显示桌宠", "Show companion"),
    ("pet_show_note", "关闭后桌宠窗口隐藏，动画状态保留。", "Hiding keeps the animation state; the window simply disappears."),
    ("pet_hints", "消息气泡", "Message bubbles"),
    ("pet_hints_note", "桌宠在任务完成或出错时显示提示气泡。", "The companion shows a bubble when a task finishes or fails."),
    ("pet_scale", "缩放档位", "Scale step"),
    ("pet_scale_note", "由桌宠窗口的位置与缩放控制，此处只读。", "Owned by the companion window; read-only here."),
    ("pet_library_title", "形象库", "Library"),
    ("pet_library_subtitle", "导入、选择或删除桌宠形象包。", "Import, pick or delete companion packages."),
    ("pet_library_note", "支持导入 .zip 形象包，选择后立即生效。", "Import a .zip package; selecting one applies immediately."),
    ("pet_library_empty", "还没有形象包，先导入一个。", "No packages yet — import one to begin."),
    ("pet_open_library", "打开形象库", "Open library"),
    ("pet_import", "导入形象包", "Import package"),
    ("pet_in_use", "使用中", "In use"),
    ("cron_new_job", "新建任务", "New task"),

    # ---- general preferences ----
    ("st_theme", "主题", "Theme"),
    ("st_theme_light", "浅色（蜂巢基调）", "Light (hive tone)"),
    ("st_send_key", "发送键", "Send key"),
    ("st_send_enter", "Enter 发送", "Enter sends"),
    ("st_send_ctrl_enter", "Ctrl+Enter 发送", "Ctrl+Enter sends"),
    ("st_send_enter_newline", "Enter 换行，Ctrl+Enter 发送", "Enter newline, Ctrl+Enter sends"),
    ("st_send_enter_direct", "Enter 直接发送", "Enter sends directly"),
    ("st_save_prefs", "保存偏好", "Save preferences"),
    ("st_nav_subtitle", "客户端偏好与系统设置", "Client preferences and system settings"),
    ("st_send_button", "仅按钮发送", "Button click only"),
    ("st_send_button_note", "Enter 换行，点击发送按钮发送", "Enter inserts a newline; click the send button to send"),
    ("st_ui_language", "语言", "Language"),
    ("st_palette", "配色主题", "Color theme"),
    ("st_palette_note", "选择系统设置的主色风格", "Pick the primary accent style"),
    ("st_palette_terracotta", "赭橙（蜂巢基调）", "Terracotta (hive base)"),
    ("st_palette_hula", "Hula 绿", "Hula green"),
    ("st_palette_minimal", "极简", "Minimal"),
    ("st_palette_tech", "科技蓝", "Tech blue"),
    ("st_font_size", "字体大小", "Font size"),
    ("st_font_size_note", "聊天内容的字体大小", "Font size for chat content"),
    ("st_version_title", "当前版本", "Current version"),
    ("st_version_latest", "已是最新版本", "You are on the latest version"),
    ("st_version_number", "版本号", "Version"),

    # ---- runtime ----
    ("st_workspace_root", "工作区根目录", "Workspace root"),
    ("st_workdir", "工作目录", "Working directory"),
    ("st_workdir_note", "更改工作目录后会使用新的文件根目录，原目录的文件不会自动迁移。",
     "Changing the working directory switches to a new file root; files in the previous directory are not migrated."),
    ("st_language", "运行时语言", "Runtime language"),
    ("st_language_hint", "zh-CN 或 en-US", "zh-CN or en-US"),
    ("st_exec_paths", "执行文件路径", "Executable paths"),
    ("st_exec_paths_note", "指定 Python / Git / rg 可执行文件路径，保存后对新启动的工具立即生效；留空表示自动检测。也可将补充包解压到安装目录的 opt/ 下自动识别。",
     "Set Python / Git / rg executable paths; saved paths apply to newly started tools immediately. Empty means auto-detect. Supplement packages unpacked under the install directory's opt/ are also detected."),
    ("st_python_path", "Python 路径", "Python path"),
    ("st_python_hint", "留空自动检测，可指向 python 可执行文件", "Empty auto-detects; may point to a python executable"),
    ("st_git_path", "Git 路径", "Git path"),
    ("st_git_hint", "留空使用系统 PATH 中的 git", "Empty uses git from the system PATH"),
    ("st_rg_path", "rg 路径", "rg path"),
    ("st_rg_hint", "留空自动检测 ripgrep", "Empty auto-detects ripgrep"),
    ("st_browse", "选择…", "Browse…"),
    ("st_supplement_import", "导入补充包…", "Import supplement…"),
    ("st_supplement_importing", "正在导入…", "Importing…"),

    # ---- LAN ----
    ("st_lan_title", "内网通信", "LAN mesh"),
    ("st_lan_on", "已启用节点发现", "Node discovery enabled"),
    ("st_lan_off", "未启用节点发现", "Node discovery disabled"),
    ("st_lan_node_name", "节点名称", "Node name"),
    ("st_lan_node_name_hint", "本机在内网中的显示名称", "Display name of this machine on the LAN"),
    ("st_lan_node_id", "节点 ID：", "Node ID: "),
    ("st_lan_listen", "监听：", "Listening: "),
    ("st_lan_discovered_prefix", "  ·  已发现 ", "  ·  discovered "),
    ("st_lan_discovered_suffix", " 个节点", " nodes"),
    ("st_lan_empty", "暂无已发现节点", "No discovered nodes"),
    ("st_lan_enable", "启用内网通信", "Enable LAN mesh"),
    ("st_lan_disable", "停用内网通信", "Disable LAN mesh"),

    # ---- models ----
    ("st_models_loading", "正在加载模型…", "Loading models…"),
    ("st_models_empty", "尚未配置模型", "No models configured"),
    ("st_models_list_title", "配置列表", "Config list"),
    ("st_models_save", "保存配置", "Save config"),
    ("st_models_subtitle", "配置对话、嵌入、声转文、语音、绘图与视频模型。不同类型只展示实际需要的参数，保存后立即生效。",
     "Configure chat, embedding, ASR, TTS, image and video models. Each type only shows the parameters it needs; changes apply right after saving."),
    ("st_models_no_info", "暂无信息", "No info"),
    ("st_models_default_badge", "默认", "Default"),
    ("st_pick_model", "选择左侧模型查看配置", "Pick a model on the left to view its settings"),
    ("st_model_new_hint", "填写基础设置后保存即可生效。", "Fill in the basic settings and save to apply."),
    ("st_model_colon", "模型：", "Model: "),
    ("st_is_default", "当前默认", "Current default"),
    ("st_set_default", "设为默认", "Set as default"),
    ("st_models_note", "模型配置保存在本机，修改后在新任务中生效。",
     "Model settings are stored locally and apply to new tasks after changes."),
    ("st_model_section_basic", "基础设置", "Basic settings"),
    ("st_model_type_label", "模型类型", "Model type"),
    ("st_type_llm", "语言模型", "Language model"),
    ("st_type_embedding", "嵌入模型", "Embedding model"),
    ("st_type_asr", "语音识别", "Speech-to-text"),
    ("st_type_tts", "语音合成", "Text-to-speech"),
    ("st_type_image", "图像生成", "Image generation"),
    ("st_type_video", "视频生成", "Video generation"),
    ("st_params_llm", "生成参数", "Generation parameters"),
    ("st_params_asr", "语音识别参数", "Speech recognition parameters"),
    ("st_params_tts", "语音合成参数", "Speech synthesis parameters"),
    ("st_params_image", "图像生成参数", "Image generation parameters"),
    ("st_params_video", "视频生成参数", "Video generation parameters"),
    ("st_params_empty_hint", "该类型只需基础设置，无额外参数。", "This type only needs the basic settings."),
    ("st_param_timeout", "超时（秒）", "Timeout (s)"),
    ("st_param_max_output", "最大输出 token", "Max output tokens"),
    ("st_param_thinking", "思考 token 预算", "Thinking token budget"),
    ("st_param_max_rounds", "最大工具轮次", "Max tool rounds"),
    ("st_param_max_context", "上下文长度", "Context length"),
    ("st_param_context_hint", "探测或留空", "Probe or leave empty"),
    ("st_param_model_default", "留空使用模型默认", "Leave empty for the model default"),
    ("st_param_default_option", "默认", "Default"),
    ("st_param_asr_language", "识别语言", "Language"),
    ("st_param_asr_language_hint", "例如：zh / en", "e.g. zh / en"),
    ("st_param_asr_format", "返回格式", "Response format"),
    ("st_param_asr_prompt", "转写提示", "Transcription prompt"),
    ("st_param_tts_voice", "音色", "Voice"),
    ("st_param_tts_format", "音频格式", "Audio format"),
    ("st_param_tts_speed", "语速", "Speed"),
    ("st_param_tts_instructions", "语音风格", "Voice style"),
    ("st_param_image_size", "图片尺寸", "Image size"),
    ("st_param_image_size_hint", "例如：1024x1024", "e.g. 1024x1024"),
    ("st_param_image_format", "输出格式", "Output format"),
    ("st_param_image_steps", "采样步数", "Sampling steps"),
    ("st_param_image_guidance", "引导系数", "Guidance scale"),
    ("st_param_negative", "负向提示词", "Negative prompt"),
    ("st_param_video_size", "视频尺寸", "Video size"),
    ("st_param_video_size_hint", "例如：832x480", "e.g. 832x480"),
    ("st_param_video_seconds", "时长（秒）", "Duration (s)"),
    ("st_tools_elsewhere", "工具目录和技能能力已在工具页面统一展示。",
     "The tool catalog and skill capabilities are shown on the tools page."),

    # ---- help / about / diagnostics ----
    ("st_help_native_note", "桌面端使用本地原生运行时，不经本机 HTTP/WebSocket，不拉起 bridge 子进程。",
     "The desktop app runs a local native runtime: no local HTTP/WebSocket hop and no bridge subprocess."),
    ("st_diagnostics", "诊断", "Diagnostics"),
    ("st_export_diagnostics", "导出诊断信息", "Export diagnostics"),
    ("st_diagnostics_note", "导出密钥无关的本机设置与能力计数，便于问题排查。",
     "Exports secret-free local settings and capability counts for troubleshooting."),
    ("st_reset_title", "重置工作状态", "Reset work state"),
    ("st_reset_note", "清理运行状态、队列与临时投影；保留资产、配置、文件与历史。",
     "Clears run state, queues and temporary projections; keeps assets, settings, files and history."),

    # ---- prompt packs ----
    ("pm_readonly_builtin", "内置只读", "Built-in (read-only)"),
    ("pm_pack", "模板包", "Pack"),
    ("pm_set_active", "设为启用", "Set active"),
    ("pm_active_tag", "当前启用：", "Active: "),
    ("pm_lang_default_tag", "系统语言默认", "System language default"),
    ("pm_sync_tag", "同步系统模板包：", "Synced from system pack: "),
    ("pm_preview_refresh", "刷新预览", "Refresh preview"),
    ("pm_preview_title", "提示词预览", "Prompt preview"),
    ("pm_preview_hint", "按当前配置拼接后的完整系统提示词", "The full system prompt assembled from the current configuration"),
    ("pm_custom", "自定义", "Custom"),
    ("pm_builtin_lang_pack", "内置语言包", "Built-in language pack"),
    ("pm_empty", "暂无提示词包", "No prompt packs"),
    ("pm_new", "新建", "New"),
    ("pm_delete_custom", "删除当前自定义包", "Delete the current custom pack"),
    ("pm_segment_edit", "分段编辑", "Segment editor"),
    ("pm_segment_edit_prefix", "分段编辑 · ", "Segment editor · "),
    ("pm_readonly_hint", "只读（内置包）", "Read-only (built-in pack)"),
    ("pm_editable_hint", "可编辑", "Editable"),
    ("pm_segment_role", "角色", "Role"),
    ("pm_segment_engineering", "工程", "Engineering"),
    ("pm_segment_tool_protocol", "工具协议", "Tool protocol"),
    ("pm_segment_skill_protocol", "技能协议", "Skill protocol"),
    ("pm_segment_memory", "记忆", "Memory"),
    ("pm_segment_attach", "附加", "Attachment"),
    ("pm_save_segment", "保存分段", "Save segment"),

    # ---- files page ----
    ("fl_title", "文件工作区", "File workspace"),
    ("fl_workspace_title", "工作目录", "Workspace directory"),
    ("fl_user_container", "用户目录", "User directory"),
    ("fl_user_container_sub", "技能等私有文件", "Private files such as skills"),
    ("fl_workdir_prefix", "工作目录 ", "Workspace "),
    ("fl_container_prefix", "容器 #", "Container #"),
    ("fl_up", "上一级", "Up"),
    ("fl_current_dir", "当前目录", "Current directory"),
    ("fl_workspace_root", "工作区根目录", "Workspace root"),
    ("fl_subdirs", "子目录", "Subdirectories"),
    ("fl_reading", "正在读取…", "Reading…"),
    ("fl_empty", "暂无子目录", "No subdirectories"),
    ("fl_total_prefix", "共 ", "Total "),
    ("fl_total_suffix", " 项 · 文件访问受当前容器根目录限制",
     " items · file access is limited to the current container root"),
    ("fl_switch_dir", "切换目录", "Switch directory"),
    ("fl_search", "搜索文件", "Search files"),
    ("fl_kind_text", "文本", "Text"),
    ("fl_kind_sheet", "表格", "Sheet"),
    ("fl_kind_deck", "演示", "Slides"),
    ("fl_kind_diagram", "流程图", "Diagram"),
    ("fl_ops", "文件操作", "File actions"),
    ("fl_preview_loading", "正在读取文件…", "Reading file…"),
    ("fl_no_file_selected", "当前目录没有文件", "No file in this directory"),
    ("fl_page_from_prefix", "第 ", "From item "),
    ("fl_page_from_suffix", " 项起", ""),
    ("fl_copy_to", "复制到", "Copy to"),
    ("fl_move_to", "移动到", "Move to"),
    ("fl_open_native", "使用系统程序打开", "Open with system"),
    ("fl_move", "移动", "Move"),
    ("fl_delete_prefix", "将永久删除“", "This permanently deletes “"),
    ("fl_delete_suffix", "”。此操作无法恢复。", "”. This cannot be undone."),
    ("fl_new_name", "新名称", "New name"),
    ("fl_target_path", "目标相对路径", "Target relative path"),
    ("fl_upload", "上传文件", "Upload file"),
    ("fl_download", "下载到本机", "Download to this machine"),
    ("fl_properties", "属性", "Properties"),
    ("fl_name", "名称", "Name"),
    ("fl_type", "类型", "Type"),
    ("fl_path", "路径", "Path"),
    ("fl_size", "大小", "Size"),
    ("fl_modified", "修改时间", "Modified"),
    ("fl_file", "文件", "File"),
    ("fl_folder", "文件夹", "Folder"),

    # ---- cloud account (§6.1) ----
    ("st_cl_title", "云端账户", "Cloud account"),
    ("st_cl_subtitle", "登录后可使用云端模型与共享额度", "Sign in to use cloud models and the shared quota"),
    ("st_cl_server", "服务地址", "Server address"),
    ("st_cl_username", "用户名", "Username"),
    ("st_cl_username_hint", "登录账号", "Account name"),
    ("st_cl_password", "密码", "Password"),
    ("st_cl_password_hint", "密码不落盘", "Never stored"),
    ("st_cl_login", "登录", "Sign in"),
    ("st_cl_relogin", "重新登录", "Sign in again"),
    ("st_cl_logging_in", "连接中…", "Connecting…"),
    ("st_cl_logout", "登出", "Sign out"),
    ("st_cl_refresh", "刷新额度", "Refresh quota"),
    ("st_cl_offline_hint", "未登录。填写服务地址与账号后登录，即可使用云端模型。",
     "Not signed in. Fill in the server and account, then sign in to use cloud models."),
    ("st_cl_expired", "登录已过期，请重新登录", "Session expired, please sign in again"),
    ("st_cl_quota_prefix", "剩余额度", "Balance"),
    ("st_cl_concurrency_prefix", "并发", "Concurrency"),
    ("st_cl_connected", "已连接", "Connected"),
    ("st_cl_reconnecting", "重连中…", "Reconnecting…"),
    ("st_cl_logged_out", "未登录", "Signed out"),
    ("st_cl_retry", "重试连接", "Retry connection"),
    ("st_cl_retry_in", "{}后重试", "Retry in {}", ["when"]),
    ("st_cl_quota_expired", "已过期", "Expired"),
    ("st_cl_sync", "同步基础设置", "Sync basic settings"),
    ("st_cl_sync_note", "登录后同步主题、头像与发送键等基础偏好。",
     "Syncs theme, avatar and send-key preferences while signed in."),
    ("st_cl_badge", "云", "Cloud"),
    ("st_cl_remove", "移除云模型", "Remove cloud model"),
    ("st_cl_locked_note", "云模型由引擎管理：登录后自动刷新，断开云端（登出）后自动移除。",
     "Cloud models are engine-managed: refreshed on sign-in, removed after sign-out."),
    ("st_cl_login_needed", "登录后可用", "Sign in to use"),
    ("st_cl_queue_prefix", "云端排队中，前方 ", "Cloud queue — "),
    ("st_cl_queue_suffix", " 人", " ahead"),
    # ---- status dock (activity capsule above the goal banner) ----
    # The runtime publishes Chinese state phrases; the dock matches them by
    # their zh prefix (I18n values) to re-render in the active locale.
    ("dock_state_queue", "模型请求正在排队", "Model request queued"),
    ("dock_state_thinking", "正在思考…", "Thinking…"),
    ("dock_state_generating", "正在生成…", "Generating…"),
    ("dock_state_tool", "正在执行工具…", "Running tools…"),
    ("dock_state_compaction", "上下文压缩中…", "Compacting context…"),
    ("dock_state_await", "模型响应中", "Waiting for the model"),
    ("dock_queue_prefix", "模型请求正在排队 · 前方 ", "Model request queued — "),
    ("dock_queue_suffix", " 个任务", " tasks ahead"),
    ("dock_steps", "步骤", "Steps"),
    ("dock_files_suffix", " 个文件已修改", " files changed"),
    ("dock_plan_title", "执行计划", "Execution plan"),
    ("dock_plan_more_prefix", "…等 ", "…and "),
    ("dock_plan_more_suffix", " 步", " more steps"),
    # slint-viewer demo values; the native projection replaces them on connect.
    ("dock_demo_explain", "已根据目标拆解为以下步骤，将逐项执行并汇报。", "The goal is broken into the steps below; they run one by one and report back."),
    ("dock_demo_step_1", "梳理需求并拆解任务", "Review the request and break it down"),
    ("dock_demo_step_2", "修改相关文件", "Modify the relevant files"),
    ("dock_demo_step_3", "运行检查并汇报结果", "Run checks and report the result"),
]
