# -*- coding: utf-8 -*-
# slint-viewer preview fixtures (commands / thread log / markdown / workflow).

ENTRIES = [
    # commands_preview.slint
    ("cpv_goal_sample", "/goal 示例目标", "/goal sample goal"),
    ("cpv_context_compact", "上下文压缩", "Context compaction"),
    ("cpv_keep_hint", "保留已完成步骤、待处理事项和相关约束。", "Keeps finished steps, pending items and constraints."),
    ("cpv_before", "压缩前 24000 tokens（75.0%）", "Before 24000 tokens (75.0%)"),
    ("cpv_after", "压缩后 8000 tokens（25.0%）", "After 8000 tokens (25.0%)"),
    ("cpv_wait_writeback", "压缩后等待模型回写", "Waiting for the model to write back after compaction"),
    ("cpv_failed", "压缩失败", "Compaction failed"),
    ("cpv_done", "压缩完成", "Compaction done"),
    ("cpv_hint", "压缩提示", "Compaction notice"),
    ("cpv_model_output", "压缩模型输出", "Compacted model output"),
    ("cpv_retry_hint", "可重试压缩；如持续超限，请减少输入或新建线程。", "Retry compaction; if it keeps overrunning, shorten input or start a new thread."),
    ("cpv_injected", "实际注入上下文", "Actually injected context"),
    ("cpv_step_done", "已完成示例检查。下一步验证输出，保持原有接口。", "Sample check finished. Next: verify output while keeping the interface."),
    ("cpv_model_unavailable", "示例模型暂不可用", "Sample model unavailable"),
    ("cpv_sample_thread", "示例线程", "Sample thread"),
    ("cpv_wait_measure", "等待实测", "Awaiting measurement"),
    ("cpv_goal", "目标", "Goal"),
    ("cpv_trigger", "触发原因：手动压缩", "Trigger: manual compaction"),
    ("cpv_manual_compact", "手动压缩", "Manual compaction"),
    ("cpv_goal_elapsed_demo", "29小时42分20秒", "29h 42m 20s"),
    # thread_log_preview.slint
    ("tlp_speed_33", "3.3k token/秒", "3.3k tokens/s"),
    ("tlp_speed_70", "70.7 token/秒", "70.7 tokens/s"),
    ("tlp_events", "事件", "Events"),
    ("tlp_all_types", "全部类型", "All types"),
    ("tlp_tool_raw", "工具：read_file\\n路径：example.txt\\n状态：completed", "Tool: read_file\\nPath: example.txt\\nStatus: completed"),
    ("tlp_done", "已完成", "Completed"),
    ("tlp_received", "已接收请求，开始处理。", "Request received, processing started."),
    ("tlp_organize", "整理示例文件", "Organize sample files"),
    ("tlp_user_name", "用户名称", "User name"),
    ("tlp_user_turn_1", "用户轮次 1", "User turn 1"),
    ("tlp_user_turn_2", "用户轮次 2", "User turn 2"),
    ("tlp_sample_user", "示例用户", "Sample user"),
    ("tlp_sample_user_msg", "示例用户消息", "Sample user message"),
    ("tlp_sample_final", "示例终态", "Sample final state"),
    ("tlp_sample_result", "示例结果", "Sample result"),
    ("tlp_sample_progress", "示例进度详情", "Sample progress detail"),
    ("tlp_page_info", "第 1 页 · 1-2 / 2 轮", "Page 1 · 1-2 / 2 turns"),
    ("tlp_thread_id", "线程 ID", "Thread ID"),
    ("tlp_title", "线程日志 · 示例线程", "Thread log · sample thread"),
    ("tlp_read_file", "读取示例文件", "Read sample file"),
    ("tlp_prefill_speed", "预填充速度", "Prefill speed"),
    ("tlp_quota", "额度消耗", "Quota used"),
    ("tlp_ttft", "首字延迟", "First token latency"),
    # markdown_preview.slint
    ("mdp_native_md", "Markdown 原生展示", "Native Markdown"),
    ("mdp_lists", "• 无序项目   ☑ 已完成任务   ☐ 待办任务", "• Bullet   ☑ Done task   ☐ To-do task"),
    ("mdp_code_block", "代码块", "Code block"),
    ("mdp_keep_indent", "保留缩进与换行", "Keep indentation and line breaks"),
    ("mdp_formula", "公式保留源码：$x^2 + y^2$", "Formulas keep source: $x^2 + y^2$"),
    ("mdp_native_cell", "原生单元格", "Native cells"),
    ("mdp_image", "图片：本地示例", "Image: local sample"),
    ("mdp_display", "展示", "Display"),
    ("mdp_quote", "引用内容独立展示，文字完整保留。", "Quotes render separately with full text."),
    ("mdp_inline", "段落包含 **粗体**、*斜体*、~~删除线~~、代码和 [链接](https://example.invalid)。", "Paragraph with **bold**, *italic*, ~~strike~~, code and [link](https://example.invalid)."),
    ("mdp_copy_alone", "独立复制", "Copy separately"),
    ("mdp_sample_pdf", "示例文档.pdf", "sample-doc.pdf"),
    ("mdp_sample_agent", "示例智能体", "Sample agent"),
    ("mdp_note", "说明", "Note"),
    ("mdp_wrap_hint", "长内容换行，窄窗口可横向滚动", "Long content wraps; narrow windows scroll horizontally"),
    ("mdp_element", "元素", "Element"),
    # workflow_preview.slint
    ("wvp_sample_file", "sample.rs · 更新 1 个文件", "sample.rs · update 1 file"),
    ("wvp_apply_patch", "应用补丁", "Apply patch"),
    ("wvp_run_cmd", "执行命令", "Run command"),
    ("wvp_update_stats", "更新  +1 −1", "Update  +1 −1"),
    ("wvp_no_match", "未找到匹配行", "No matching lines"),
    ("wvp_patch_failed", "补丁未应用：未找到预期上下文，请先重新读取文件。", "Patch not applied: expected context missing, re-read the file first."),
    # thread_activity_preview.slint
    ("tav_switched", "切换完成", "Switched"),
]
