# -*- coding: utf-8 -*-
# Channels page, cron page, world page, plaza page, screenshot overlay, tray.

ENTRIES = [
    # ---- channels ----
    ("ch_title", "渠道设置", "Channels"),
    ("ch_subtitle", "接入外部消息渠道账号", "Connect external messaging channel accounts"),
    ("ch_search", "搜索账号", "Search accounts"),
    ("ch_new_account", "新建账号", "New account"),
    ("ch_channel_type", "渠道类型", "Channel type"),
    ("ch_account", "账号", "Account"),
    ("ch_configured", "已配置", "Configured"),
    ("ch_pending_config", "待补全", "Incomplete"),
    ("ch_accounts_title", "渠道账号", "Channel accounts"),
    ("ch_enabled_prefix", "已启用 · ", "Enabled · "),
    ("ch_disabled_prefix", "已停用 · ", "Disabled · "),
    ("ch_config_ok", "配置完整", "Configuration complete"),
    ("ch_config_pending", "配置待补全", "Configuration incomplete"),
    ("ch_pick_account", "在左侧选择账号查看详情", "Pick an account on the left to view details"),
    ("ch_logs", "运行日志", "Run logs"),
    ("ch_reconnect", "重连", "Reconnect"),
    ("ch_pick_account_hint", "请选择渠道账号查看详情", "Select a channel account to view details"),
    ("ch_account_id", "账号 ID", "Account ID"),
    ("ch_receive_target", "接收对象", "Receivers"),
    ("ch_bind_agent", "绑定智能体", "Bound agent"),
    ("ch_secret_state", "密钥状态", "Secret state"),
    ("ch_secret_set", "已设置（不回显）", "Set (never shown)"),
    ("ch_secret_unset", "未设置", "Not set"),
    ("ch_last_updated", "最近更新", "Updated"),
    ("ch_created_prefix", "  ·  创建于 ", "  ·  created "),
    ("ch_config_summary", "配置摘要", "Configuration summary"),
    ("ch_bindings", "消息绑定", "Message bindings"),
    ("ch_bindings_count_suffix", " 条", ""),
    ("ch_bindings_all_sessions", "全部会话", "All sessions"),
    ("ch_disabled_suffix", " · 已停用", " · disabled"),
    ("ch_delete_binding", "删除绑定", "Delete binding"),
    ("ch_bindings_empty", "暂无绑定记录", "No bindings"),
    ("ch_accounts_empty", "暂无渠道账号", "No channel accounts"),
    ("ch_no_channels", "暂无可用渠道", "No channels available"),
    ("ch_display_name", "显示名称", "Display name"),
    ("ch_enable_account", "启用账号", "Enable account"),
    ("ch_receive_group", "接收群聊", "Receive group chats"),
    ("ch_group_chat", "群聊", "Group chat"),
    ("ch_direct_chat", "单聊", "Direct chat"),
    ("ch_field_feishu_app_id", "飞书应用 App ID", "Feishu app ID"),
    ("ch_field_app_secret", "App Secret（留空保留原值）", "App secret (leave empty to keep)"),
    ("ch_field_writeonly_hint", "仅写入，不回显", "Write-only, never shown"),
    ("ch_field_feishu_domain", "域名（可选，默认 open.feishu.cn）", "Domain (optional, default open.feishu.cn)"),
    ("ch_field_corp_id", "企业 ID（corp_id）", "Corp ID (corp_id)"),
    ("ch_field_wecom_corp_id", "企业微信 Corp ID", "WeCom Corp ID"),
    ("ch_field_wecom_agent_id", "应用 AgentId", "App AgentId"),
    ("ch_field_wecom_agent_suffix", "企业微信应用 AgentId", "WeCom app AgentId"),
    ("ch_field_wecom_secret", "应用 Secret（留空保留原值）", "App secret (leave empty to keep)"),
    ("ch_field_wecom_domain", "域名（可选，默认 qyapi.weixin.qq.com）", "Domain (optional, default qyapi.weixin.qq.com)"),
    ("ch_field_mp_app_id", "公众号 App ID", "Official account AppID"),
    ("ch_field_token_optional", "Token（可选）", "Token (optional)"),
    ("ch_field_token_hint", "回调 Token，可留空", "Callback token, optional"),
    ("ch_field_aes_optional", "EncodingAESKey（可选）", "EncodingAESKey (optional)"),
    ("ch_field_aes_hint", "回调加密键，可留空", "Callback encryption key, optional"),
    ("ch_field_mp_original_id", "原始 ID（可选）", "Original ID (optional)"),
    ("ch_field_mp_original_hint", "公众号原始 ID gh_ 前缀", "Official account original ID with gh_ prefix"),
    ("ch_field_mp_domain", "域名（可选，默认 api.weixin.qq.com）", "Domain (optional, default api.weixin.qq.com)"),
    ("ch_field_api_base_optional", "服务地址（可选）", "API base URL (optional)"),
    ("ch_field_bot_token", "Bot Token（留空保留原值）", "Bot token (leave empty to keep)"),
    ("ch_no_token_hint", "没有 Token？", "No token?"),
    ("ch_qr_login_button", "扫码登录获取", "Scan QR to sign in"),
    ("ch_field_bot_id", "机器人 ID", "Bot ID"),
    ("ch_field_bot_id_placeholder", "ilink 机器人 ID", "ilink bot ID"),
    ("ch_field_user_id", "用户 ID（可选）", "User ID (optional)"),
    ("ch_field_user_id_placeholder", "ilink 用户 ID", "ilink user ID"),
    ("ch_advanced_json", "高级配置 JSON（合并进渠道配置，留空跳过）", "Advanced JSON (merged into the channel config; leave empty to skip)"),
    ("ch_guided_form_empty", "该渠道暂无引导表单，请在下方高级配置中填写 JSON 字段。", "This channel has no guided form; fill the JSON fields in advanced settings below."),
    ("ch_logs_empty", "暂无运行日志", "No run logs"),
    ("ch_bindings_limit_suffix", " 条（上限 200）", " (up to 200)"),
    ("ch_delete_message", "将删除该账号及其全部绑定，删除后需要重新扫码或填写配置才能恢复接收。确认删除？",
     "This deletes the account and all its bindings; receiving requires a new QR sign-in or manual configuration afterwards. Delete now?"),
    ("ch_qr_title", "微信扫码登录", "WeChat QR sign-in"),
    ("ch_qr_waiting", "正在获取二维码…", "Fetching QR code…"),
    ("ch_qr_scan_hint", "请使用微信扫描二维码", "Scan the QR code with WeChat"),
    ("ch_qr_success", "扫码成功，已回填登录凭据。请检查账号信息后保存。", "Signed in. Credentials filled in; review the account and save."),
    ("ch_qr_expired", "二维码已过期，请重新获取。", "The QR code expired; fetch a new one."),
    ("ch_qr_canceled", "已取消扫码登录。", "QR sign-in canceled."),
    ("ch_qr_failed_prefix", "扫码登录失败：", "QR sign-in failed: "),
    ("ch_qr_refresh", "重新获取二维码", "Fetch new QR code"),

    # ---- cron ----
    ("cr_title", "定时任务", "Scheduled tasks"),
    ("cr_subtitle", "查看与管理智能体定时任务", "View and manage agent scheduled tasks"),
    ("cr_search", "搜索任务", "Search tasks"),
    ("cr_new_task", "新建任务", "New task"),
    ("cr_next_prefix", " · 下次 ", " · next "),
    ("cr_empty", "暂无定时任务", "No scheduled tasks"),
    ("cr_pick_task", "在左侧选择任务查看详情", "Pick a task on the left to view details"),
    ("cr_run_now", "立即运行", "Run now"),
    ("cr_runs", "运行记录", "Runs"),
    ("cr_pick_task_hint", "请选择任务查看详情", "Select a task to view details"),
    ("cr_schedule", "调度", "Schedule"),
    ("cr_next_run", "下次执行", "Next run"),
    ("cr_last_status", "上次状态", "Last status"),
    ("cr_never_run", "尚未运行", "Never run"),
    ("cr_last_error", "上次错误", "Last error"),
    ("cr_disable_task", "停用任务", "Disable task"),
    ("cr_enable_task", "启用任务", "Enable task"),
    ("cr_delete_task", "删除任务", "Delete task"),
    ("cr_runs_title_prefix", "运行记录 · ", "Runs · "),
    ("cr_runs_recent_prefix", "最近 ", "Last "),
    ("cr_runs_recent_suffix", " 次（最多 200 条）", " runs (up to 200)"),
    ("cr_trigger_manual", "手动", "Manual"),
    ("cr_trigger_schedule", "计划", "Scheduled"),
    ("cr_no_summary", "无输出摘要", "No output summary"),
    ("cr_failure_prefix", "失败：", "Failed: "),
    ("cr_runs_empty", "暂无运行记录", "No runs"),
    ("cr_kind_once", "一次性", "One-off"),
    ("cr_kind_interval", "固定间隔", "Fixed interval"),
    ("cr_kind_cron", "Cron 表达式", "Cron expression"),
    ("cr_field_exec_time", "执行时间", "Run at"),
    ("cr_field_interval", "间隔（秒）", "Interval (seconds)"),
    ("cr_field_first_time", "首次时间", "First run at"),
    ("cr_field_expression", "表达式", "Expression"),
    ("cr_field_timezone", "时区", "Time zone"),
    ("cr_field_message", "执行消息", "Message"),
    ("cr_field_target_agent", "目标智能体", "Target agent"),
    ("cr_delete_after_run", "运行一次后删除", "Delete after one run"),

    # ---- world ----
    ("wd_groups", "群组", "Groups"),
    ("wd_contacts", "联系人", "Contacts"),
    ("wd_groups_subtitle", "普通用户群组消息", "Regular user group messages"),
    ("wd_contacts_subtitle", "与联系人单聊", "Direct chats with contacts"),
    ("wd_new_group", "新建群组", "New group"),
    ("wd_pick_members_hint", "选择至少 1 名初始成员（不含你自己）", "Pick at least 1 initial member (excluding yourself)"),
    ("wd_loading_contacts", "正在加载联系人…", "Loading contacts…"),
    ("wd_no_pickable", "暂无可选联系人", "No contacts to pick"),
    ("wd_search_groups", "搜索群组", "Search groups"),
    ("wd_search_contacts", "搜索联系人", "Search contacts"),
    ("wd_online", "在线", "Online"),
    ("wd_no_messages", "暂无消息", "No messages yet"),
    ("wd_members_suffix", " 人 · ", " members · "),
    ("wd_empty", "暂无数据", "No data"),
    ("wd_group_messages", "群组消息", "Group messages"),
    ("wd_user_messages", "用户消息", "User messages"),
    ("wd_announcement", "公告", "Announcement"),
    ("wd_no_announcement", "暂无公告", "No announcement"),
    ("wd_members", "成员", "Members"),
    ("wd_multiline_hint", "支持多行，最多 4000 字", "Multiple lines, up to 4000 characters"),
    ("wd_pick_group_hint", "选择一个普通用户群组查看消息。", "Pick a regular user group to view messages."),
    ("wd_pick_contact_hint", "选择联系人开始单聊。", "Pick a contact to start a direct chat."),
    ("wd_load_earlier", "加载更早", "Load earlier"),
    ("wd_members_title_prefix", "群成员 · ", "Members · "),
    ("wd_collapse_members", "收起成员列表", "Collapse member list"),
    ("wd_owner", "群主", "Owner"),
    ("wd_loading_members", "正在加载成员…", "Loading members…"),
    ("wd_members_empty", "暂无成员信息", "No member info"),

    # ---- plaza ----
    ("pz_title", "广场", "Plaza"),
    ("pz_subtitle", "浏览普通资产并导入", "Browse and import regular assets"),
    ("pz_refresh", "刷新广场", "Refresh plaza"),
    ("pz_kind_filter", "资产类型", "Asset type"),
    ("pz_assets", "资产", "Assets"),
    ("pz_mine", "我发布的", "Published by me"),
    ("pz_loading", "正在加载广场…", "Loading plaza…"),
    ("pz_empty", "广场暂无普通资产", "No regular assets in the plaza"),
    ("pz_from_prefix", "来自 ", "From "),
    ("pz_pick_item", "在左侧选择资产查看详情", "Pick an asset on the left to view details"),
    ("pz_import", "导入资产", "Import asset"),
    ("pz_pick_hint", "选择资产查看详情，导入后即可使用。蜂群相关资产仅在网页端提供。",
     "Pick an asset to view details; it is ready to use after import. Hive-related assets are only available on the web client."),
    ("pz_publisher", "发布者", "Publisher"),
    ("pz_me_prefix", "我（", "Me ("),
    ("pz_updated_at", "更新时间", "Updated"),
    ("pz_kind", "文件", "File"),
    ("pz_sync_state", "同步状态", "Sync state"),
    ("pz_sync_current", "与源一致", "Up to date with source"),
    ("pz_sync_outdated", "源已更新，重新导入可获取新版本", "Source updated; import again to get the new version"),
    ("pz_sync_deleted", "源已删除，仅可导入当前快照", "Source deleted; only the current snapshot can be imported"),
    ("pz_tags", "标签", "Tags"),
    ("pz_summary", "简介", "Summary"),
    ("pz_no_summary", "暂无简介", "No summary"),
    ("pz_import_note", "导入工蜂卡会创建一个新的专家；导入技能包会安装到本机技能目录。导入动作会经过运行时权限校验。",
     "Importing a worker card creates a new agent; importing a skill pack installs it into the local skill directory. Imports go through runtime permission checks."),
    ("pz_import_title", "导入广场资产", "Import plaza asset"),
    ("pz_import_prefix", "将导入“", "This imports “"),
    ("pz_import_card_suffix", "会创建一个新的专家。", "” and creates a new agent."),
    ("pz_import_pack_suffix", "会安装技能包到本机。", "” and installs the skill pack locally."),
    ("pz_import_question", "确认导入？", "Import now?"),
    ("pz_confirm_import", "确认导入", "Import"),

    # ---- screenshot overlay ----
    ("so_hint", "拖动选择截图区域 · 右键或 Esc 取消", "Drag to select a region · right-click or Esc to cancel"),
    ("so_fullscreen", "全屏", "Fullscreen"),

    # ---- tray ----
    ("tr_title", "心舰 · 蜂巢", "Wunder · Hive"),
    ("tr_name", "心舰", "Wunder"),
    ("tr_show_window", "显示主窗口", "Show main window"),
    ("tr_screenshot", "截图 (Ctrl+F1)", "Screenshot (Ctrl+F1)"),
    ("tr_fullscreen_shot", "全屏截图", "Fullscreen screenshot"),
    ("tr_exit", "退出", "Exit"),

    # ---- window ----
    ("app_window_title", "心舰 · 蜂巢（Slint 原型）", "Wunder · Hive (Slint prototype)"),
]
