# -*- coding: utf-8 -*-
# Composer (chat input), message row and components labels.

ENTRIES = [
    # ---- composer ----
    ("cp_thinking_auto", "自动", "Auto"),
    ("cp_context_usage", "上下文占用", "Context usage"),
    ("cp_usage_empty", "暂无最近一次请求数据", "No request usage yet"),
    ("cp_usage_prefix", "当前请求上下文占用：", "Current context usage: "),
    ("cp_thinking_level", "思考等级", "Thinking level"),
    ("dk_new_folder", "新建文件夹", "New folder"),
    ("cp_effort_default", "默认（跟随模型）", "Default (model default)"),
    ("cp_effort_none", "none（不额外思考）", "None (no extra reasoning)"),
    ("cp_effort_minimal", "minimal（极少思考）", "Minimal"),
    ("cp_effort_low", "low（低）", "Low"),
    ("cp_effort_medium", "medium（中）", "Medium"),
    ("cp_effort_high", "high（高）", "High"),
    ("cp_effort_xhigh", "xhigh（超高）", "XHigh"),
    ("cp_think_low", "低", "Low"),
    ("cp_think_mid", "中", "Medium"),
    ("cp_think_high", "高", "High"),
    ("cp_image_prefix", "图片 · ", "Images · "),
    ("cp_remove_attachment", "移除附件", "Remove attachment"),
    ("cp_input_placeholder", "输入消息，开始新的对话…", "Type a message to start…"),
    ("cp_input_placeholder_workspace", "给 {} 发送消息…（长按语音）", "Message {}… (hold to talk)", ["workspace"]),
    ("cp_preset_questions", "预设问题", "Preset questions"),
    ("cp_preset_q1", "你好，请介绍一下你的能力。", "Hi, please introduce your capabilities."),
    ("cp_preset_q2", "请帮我整理当前内容。", "Please organize the current content."),
    ("cp_commands", "命令", "Commands"),
    ("cp_cmd_help", "/help  查看可用命令", "/help  list available commands"),
    ("cp_cmd_new", "/new  新建线程", "/new  new thread"),
    ("cp_cmd_stop", "/stop  停止并退出目标态", "/stop  stop and leave goal mode"),
    ("cp_cmd_goal", "/goal  设置目标", "/goal  set a goal"),
    ("cp_cmd_compact", "/compact  压缩上下文", "/compact  compact context"),
    ("cp_usage_effort_hint", "推理强度随线程保存，切换后下一条消息即时生效；上下文占用来自最近一次请求的实际用量。", "Reasoning effort is stored per thread and applies to the next message. Context usage comes from the last request's actual usage."),
    ("cp_stop_recording", "停止录音", "Stop recording"),
    ("cp_transcribing", "识别中", "Transcribing"),
    ("cp_record", "录音", "Record"),
    ("cp_screenshot", "截图", "Screenshot"),
    ("cp_screenshot_mode", "截图方式（默认隐藏窗口）", "Capture mode (hides window by default)"),
    ("cp_shot_fullscreen_hidden", "全屏截图（隐藏窗口）", "Fullscreen (hide window)"),
    ("cp_shot_region_hidden", "区域截图（隐藏窗口）", "Region (hide window)"),
    ("cp_shot_fullscreen_kept", "全屏截图（保留窗口）", "Fullscreen (keep window)"),
    ("cp_shot_region_kept", "区域截图（保留窗口）", "Region (keep window)"),
    ("cp_stopping", "正在停止", "Stopping"),
    ("cp_stop_generation", "停止生成", "Stop"),
    ("cp_sending", "发送中", "Sending"),
    ("cp_send", "发送", "Send"),

    # ---- more menu (§8.2) ----
    ("cp_more", "更多", "More"),
    ("cp_more_new_thread", "新建线程", "New thread"),
    ("cp_more_upload", "上传文件", "Upload file"),
    ("cp_more_workspace", "打开工作区文件夹", "Open workspace folder"),
    ("cp_permission", "权限模式", "Permission mode"),
    ("cp_permission_full", "完全访问", "Full access"),
    ("cp_permission_write", "写入自动", "Auto-edit"),
    ("cp_permission_command", "执行前确认", "Confirm commands"),
    ("cp_permission_note", "与运行时 approval_mode 同名：full_auto 直接执行；auto_edit 仅放行编辑；suggest 在执行前确认。蜂窝本地链路尚未接审批往返，当前选择只记录偏好。", "Named after the runtime approval_mode: full_auto runs directly, auto_edit allows edits only, suggest confirms before executing. The local desktop path has no approval round-trip yet, so the choice is recorded as a preference only."),

    # ---- model picker (§8.3) ----
    ("cp_model", "模型", "Model"),
    ("cp_model_pick", "切换模型", "Switch model"),
    ("cp_model_search", "搜索模型", "Search models"),
    ("cp_model_empty", "还没有可用模型。请到「设置 → 模型设置」添加。", "No models yet. Add one in Settings → Models."),
    ("cp_model_no_match", "没有匹配的模型", "No matching model"),
    ("cp_model_default_tag", "默认", "Default"),
    ("cp_model_settings", "打开模型设置", "Open model settings"),
    ("cp_model_effort", "推理强度", "Reasoning effort"),
    ("cp_model_none", "未选择模型", "No model selected"),
    ("cp_effort_short_default", "默认", "Default"),
    ("cp_effort_short_none", "不思考", "None"),
    ("cp_effort_short_minimal", "极少", "Minimal"),
    ("cp_effort_short_low", "低", "Low"),
    ("cp_effort_short_medium", "中", "Medium"),
    ("cp_effort_short_high", "高", "High"),
    ("cp_effort_short_xhigh", "极高", "XHigh"),

    # ---- goal banner (§8.1b) ----
    ("cp_error_prefix", "无法", "Unable to "),
    ("cp_fail_prefix", "失败", "Failed"),
    ("cp_goal_label", "目标", "Goal"),
    ("cp_goal_pause", "暂停目标", "Pause goal"),
    ("cp_goal_resume", "继续目标", "Resume goal"),
    ("cp_goal_paused_tag", "已暂停", "Paused"),
    ("cp_goal_edit_hint", "输入新的目标内容，回车保存", "Edit the goal, Enter to save"),
    ("cp_goal_edit", "编辑目标", "Edit goal"),
    ("cp_goal_clear", "清除目标", "Clear goal"),

    # ---- status bar (§8.5) ----
    ("cp_status_local", "本地", "Local"),
    ("cp_status_branch", "分支", "Branch"),

    # ---- message row ----
    ("ms_agent_loop", "智能体循环", "Agent loop"),
    ("ms_state_done", "任务完成", "Task complete"),

    # ---- components ----
    ("ui_collapse_sidebar", "收起侧栏", "Collapse sidebar"),
    ("ui_expand_sidebar", "展开侧栏", "Expand sidebar"),
    ("ui_avatar_mine", "我", "Me"),
    ("ui_search_placeholder", "搜索", "Search"),
]
