# -*- coding: utf-8 -*-
# Shared labels and main-shell chrome (rail, menus, chat shell, dialogs).
# (key, zh, en) — zh must match UI literals exactly; en is the en-US variant.

ENTRIES = [
    # ---- common actions ----
    ("common_save", "保存", "Save"),
    ("common_saving", "保存中", "Saving…"),
    ("common_cancel", "取消", "Cancel"),
    ("common_discard", "放弃修改", "Discard"),
    ("common_delete", "删除", "Delete"),
    ("common_confirm_delete", "确认删除", "Delete"),
    ("common_refresh", "刷新", "Refresh"),
    ("common_close", "关闭", "Close"),
    ("common_create", "创建", "Create"),
    ("common_creating", "创建中", "Creating…"),
    ("common_edit", "编辑", "Edit"),
    ("common_add", "添加", "Add"),
    ("common_new", "新建", "New"),
    ("common_open", "打开", "Open"),
    ("common_copy", "复制", "Copy"),
    ("common_rename", "重命名", "Rename"),
    ("common_confirm", "确认", "Confirm"),
    ("common_search", "搜索", "Search"),
    ("common_none", "无", "None"),
    ("common_done", "完成", "Done"),
    ("common_details", "详情", "Details"),
    ("common_enable", "启用", "Enable"),
    ("common_disable", "停用", "Disable"),
    ("common_enabled", "已启用", "Enabled"),
    ("common_disabled", "已停用", "Disabled"),
    ("common_previous_page", "上一页", "Previous"),
    ("common_next_page", "下一页", "Next"),
    ("common_default_agent", "默认智能体", "Default agent"),
    ("common_default_model", "默认模型", "Default model"),
    ("common_ai", "智能体", "Agents"),
    ("common_tools", "工具", "Tools"),
    ("common_files", "文件", "Files"),
    ("common_messages", "消息", "Messages"),
    ("common_you", "你", "You"),
    ("common_me", "我", "Me"),
    ("common_directory", "目录", "Directory"),
    ("common_built_in_tools", "内置工具", "Built-in tools"),
    ("common_skills", "技能", "Skills"),
    ("common_model_config", "模型配置", "Models"),
    ("common_local_runtime", "本地运行时", "Local runtime"),
    ("common_yesterday", "昨天", "Yesterday"),
    ("common_just_now", "刚刚", "Just now"),
    ("common_unknown", "未连接", "Not connected"),
    ("common_cron_tasks", "定时任务", "Scheduled tasks"),
    ("common_groups", "群组", "Groups"),
    ("common_users", "用户", "Users"),
    ("common_more", "更多", "More"),
    ("common_name", "名称", "Name"),
    ("common_type", "类型", "Type"),
    ("common_status", "状态", "Status"),
    ("common_model", "模型", "Model"),
    ("common_agents", "专家", "Agents"),
    ("common_channels", "渠道", "Channels"),
    ("common_auto", "自动", "Auto"),
    ("common_saving_dots", "正在保存…", "Saving…"),
    ("common_loading", "正在加载…", "Loading…"),
    ("common_reading", "正在读取…", "Reading…"),

    # ---- rail ----
    ("rail_messages", "消息", "Messages"),
    ("rail_agents", "专家", "Agents"),
    ("rail_tools", "工具", "Tools"),
    ("rail_files", "文件", "Files"),
    ("rail_users", "用户", "Users"),
    ("rail_more", "更多", "More"),

    # ---- more menu ----
    ("menu_settings", "系统设置", "System settings"),
    ("menu_groups", "群组", "Groups"),
    ("menu_profile", "我的概况", "Profile"),

    # ---- chat shell ----
    ("chat_title", "消息", "Messages"),
    ("chat_subtitle", "与智能体一起，继续工作", "Keep working with your agents"),
    ("chat_search_placeholder", "搜索", "Search"),
    ("chat_new_thread", "新建线程", "New thread"),
    ("chat_connected_source", "本地运行时", "Local runtime"),
    ("chat_preview_source", "本地界面预览", "Local UI preview"),
    ("chat_back_to_latest", "回到最新消息", "Back to latest"),
    ("chat_author_you", "你", "You"),
    ("chat_demo_status", "本地演示 · 未连接后端", "Local demo · backend not connected"),
    ("chat_greeting", "你好，可以开始新的对话。", "Hi, you can start a new conversation."),

    # ---- demo fixtures (main.slint defaults; kept bilingual for preview parity) ----
    ("demo_conv0_preview", "随时开始新的对话", "Start a new conversation anytime"),
    ("demo_conv1_title", "智能体 01", "Agent 01"),
    ("demo_conv1_preview", "上次任务已完成", "Last task completed"),
    ("demo_conv2_title", "智能体 02", "Agent 02"),
    ("demo_conv2_preview", "暂无新消息", "Nothing new"),
    ("demo_agent_desc", "帮助你处理日常任务。", "Helps you handle daily tasks."),
    ("demo_agent_group", "默认蜂房", "Default hive"),
    ("demo_tool_file_desc", "读取和整理本地工作目录中的内容", "Reads and organizes the local working directory"),
    ("demo_tool_skill_name", "技能调用", "Skill calls"),
    ("demo_tool_skill_desc", "按权限使用已安装的技能", "Uses installed skills with permissions"),

    # ---- about dialog ----

    # ---- workspace binding dialog ----
    ("workspace_binding_title", "切换工作目录", "Switch working directory"),
    ("workspace_binding_index", "目录序号", "Directory index"),
    ("workspace_binding_path", "本地目录路径", "Local directory path"),
    ("workspace_binding_choose", "选择目录", "Choose directory"),

    # ---- reset confirm ----
    ("reset_title", "重置工作状态", "Reset work state"),
    ("reset_message", "将停止运行中的任务、清理队列与临时投影。资产、配置、文件与历史保留。确认重置？",
     "Running tasks will stop; queues and temporary projections will be cleared. Assets, settings, files and history are kept. Reset now?"),
    ("reset_confirm", "确认重置", "Reset"),

    # ---- thread log dialog ----
    ("thread_log_overview", "线程概况", "Thread overview"),
    ("thread_log_status_label", "状态", "Status"),
    ("thread_log_elapsed", "耗时", "Duration"),
    ("thread_log_user_rounds", "用户轮次", "User turns"),
    ("thread_log_tool_calls", "工具调用", "Tool calls"),
    ("thread_log_tokens", "Token 消耗", "Token usage"),
    ("thread_log_speed", "生成速度", "Speed"),
    ("thread_log_entries", "详情条目", "Entries"),
    ("thread_log_search", "搜索日志", "Search log"),
    ("thread_log_filter_all", "全部", "All"),
    ("thread_log_filter_tools", "工具", "Tools"),
    ("thread_log_filter_models", "模型", "Models"),

    # ---- cron delete confirm ----
    ("cron_delete_title", "删除定时任务", "Delete scheduled task"),
    ("cron_delete_message", "删除后任务与运行记录不可恢复。确认删除该任务？",
     "The task and its run records cannot be recovered after deletion. Delete this task?"),

    # ---- generic info dialog ----
    ("info_ack", "知道了", "Got it"),

    # ---- profile page ----
    ("profile_title", "我的概况", "Profile"),
    ("profile_subtitle", "账号信息与使用概览", "Account and usage overview"),
    ("profile_account_info", "账户信息", "Account"),
    ("profile_email", "邮箱", "Email"),
    ("profile_unit", "单位", "Unit"),
    ("profile_last_active", "最近活跃", "Last active"),
    ("profile_unset", "未填写", "Not set"),
    ("profile_avatar_color", "头像颜色", "Avatar color"),
    ("profile_stats_title", "使用统计", "Usage"),
    ("profile_stats_subtitle", "会话、工具与额度使用概况", "Sessions, tools and quota at a glance"),
    ("profile_edit_button", "编辑资料", "Edit profile"),
    ("profile_sessions_total", "会话总数", "Total sessions"),
    ("profile_sessions_7d", "近 7 天", "Last 7 days"),
    ("profile_tool_calls", "工具调用", "Tool calls"),
    ("profile_token_usage", "Token 使用", "Token usage"),
    ("profile_edit_title", "编辑个人资料", "Edit profile"),
    ("profile_username", "用户名", "Username"),
    ("profile_unit_optional", "单位编号（可选）", "Unit ID (optional)"),

    # ---- agent creator dialog ----
    ("agent_creator_title", "新建智能体", "New agent"),
    ("agent_creator_name_label", "名称", "Name"),
    ("agent_creator_name_placeholder", "输入智能体名称", "Enter an agent name"),

    # ---- model settings form ----
    ("model_editor_add", "添加模型", "Add model"),
    ("model_key_label", "配置名称", "Config name"),
    ("model_key_placeholder", "输入模型配置键", "Enter a model config key"),
    ("model_provider_label", "提供方预设", "Provider preset"),
    ("model_name_label", "模型名称", "Model name"),
    ("model_name_placeholder", "输入上游模型名称", "Enter the upstream model name"),
    ("model_base_url_label", "服务地址", "Base URL"),
    ("model_base_url_placeholder", "输入服务地址", "Enter the service URL"),
    ("model_token_label", "访问密钥（留空保留原值）", "API key (leave empty to keep)"),
    ("model_token_placeholder", "仅保存到本机设置", "Saved to local settings only"),
    ("model_probe_context", "探测上下文", "Probe context"),
    ("model_probe_voices", "探测语音", "Probe voices"),

    # ---- file preview dialog ----
    ("preview_edit_toggle", "取消编辑", "Cancel editing"),
    ("preview_copy", "复制", "Copy"),
    ("preview_close", "关闭预览", "Close preview"),

    # ---- workspace sidebar (two-column layout) ----
    ("sidebar_new_task", "新任务", "New task"),
    ("sidebar_workspaces", "工作区", "Workspaces"),
    ("sidebar_settings", "设置", "Settings"),
    ("sidebar_empty_hint", "尚无工作区，点击「新任务」开始", "No workspaces yet - start with New task"),
    ("ws_menu_new_thread", "新建线程", "New thread"),
    ("ws_menu_edit", "编辑工作区", "Edit workspace"),
    ("ws_menu_reveal", "打开文件夹", "Open folder"),
    ("ws_menu_delete", "删除工作区", "Delete workspace"),
    ("ws_delete_title", "删除工作区", "Delete workspace"),
    ("ws_delete_message", "不会删除磁盘上的文件。其线程将全部归档，确定删除该工作区吗？",
     "Files on disk are kept. All its threads will be archived. Delete this workspace?"),
    ("ws_delete_confirm", "删除工作区", "Delete workspace"),
    ("ws_add_title", "添加工作区", "Add workspace"),
]
