//! Static agent avatars aligned with the web catalog
//! (`frontend/src/assets/agent-avatars`). The byte textures are generated by
//! `build.rs` from `assets/agent-avatars`; decoding is cached per key like the
//! workspace file icons.

use slint::Image;
use std::cell::RefCell;
use std::collections::HashMap;

include!(concat!(env!("OUT_DIR"), "/avatar_assets_data.rs"));

/// Web default avatar key (`DEFAULT_AGENT_AVATAR_IMAGE_KEY`).
pub const DEFAULT_AVATAR_KEY: &str = "avatar-046";
/// Option key rendered as the agent-name initial letter ("默" in the dialog).
pub const INITIAL_KEY: &str = "initial";

pub fn static_avatar_keys() -> impl Iterator<Item = &'static str> {
    AVATAR_FILES.iter().map(|(key, _)| *key)
}

/// Resolve the decoded image for one avatar key; unknown keys fall back to
/// the web default so a stale config never renders an empty bubble.
pub fn static_avatar_image(key: &str) -> Image {
    let key: &'static str = AVATAR_FILES
        .iter()
        .find(|(candidate, _)| *candidate == key)
        .or_else(|| {
            AVATAR_FILES
                .iter()
                .find(|(candidate, _)| *candidate == DEFAULT_AVATAR_KEY)
        })
        .map(|(key, _)| *key)
        .unwrap_or(DEFAULT_AVATAR_KEY);
    CACHE.with(|cache| cached_image(cache, key))
}

thread_local! {
    // Decoding runs on the UI thread and slint::Image is not Send in this
    // vendored renderer build, so the cache stays thread-local (same bargain
    // as the workspace file icons).
    static CACHE: RefCell<HashMap<&'static str, Image>> = RefCell::new(HashMap::new());
}

fn cached_image(cache: &RefCell<HashMap<&'static str, Image>>, key: &'static str) -> Image {
    let mut cache = cache.borrow_mut();
    if let Some(image) = cache.get(key) {
        return image.clone();
    }
    let bytes = AVATAR_FILES
        .iter()
        .find(|(candidate, _)| *candidate == key)
        .map(|(_, bytes)| *bytes);
    let image = bytes.and_then(crate::file_icons::decode_png_image).unwrap_or_default();
    cache.insert(key, image.clone());
    image
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_is_ordered_and_complete() {
        let keys: Vec<&str> = static_avatar_keys().collect();
        assert_eq!(keys.len(), 59, "web catalog syncs 59 avatars");
        assert_eq!(keys[0], "avatar-000");
        assert!(keys.contains(&DEFAULT_AVATAR_KEY));
    }

    #[test]
    fn unknown_key_falls_back_to_default() {
        assert_eq!(
            static_avatar_image("avatar-9999"),
            static_avatar_image(DEFAULT_AVATAR_KEY)
        );
    }
}
