//! Workspace file icons aligned with the web vscode-icons theme resolver.
//! The byte textures and lookup tables are generated by `build.rs` from
//! `assets/vscode-icons/file-icon-map.json`, which
//! `scripts/sync_desktop_file_icons.py` derives from the web frontend.

use slint::Image;
use std::cell::RefCell;
use std::collections::HashMap;

include!(concat!(env!("OUT_DIR"), "/file_icons_data.rs"));

/// Resolve the icon for one workspace entry. Mirrors the web panel: folders
/// use the shared folder icon, drawio files the diagram icon, then the theme
/// extension table, then the file-name table, then the default file icon.
pub fn workspace_file_icon(name: &str, entry_type: &str) -> Image {
    CACHE.with(|cache| cached_image(cache, icon_key(name, entry_type)))
}

fn icon_key(name: &str, entry_type: &str) -> &'static str {
    if entry_type == "dir" {
        return FOLDER_ICON;
    }
    let lowered = name.to_lowercase();
    let extension = entry_extension(&lowered);
    if DIAGRAM_EXTENSIONS.contains(&extension) {
        return DIAGRAM_ICON;
    }
    // An extension hit always wins, even when it resolves to the default
    // icon: the web resolver never falls through to the file-name table.
    if let Ok(index) = EXTENSIONS.binary_search_by(|(key, _)| (*key).cmp(extension)) {
        return EXTENSIONS[index].1;
    }
    if let Ok(index) = NAMES.binary_search_by(|(key, _)| (*key).cmp(lowered.as_str())) {
        return NAMES[index].1;
    }
    DEFAULT_ICON
}

/// Same rule as the web `getWorkspaceExtension`, including the `.drawio.xml`
/// special case and hidden names whose extension starts at the first byte.
fn entry_extension(lowered_name: &str) -> &str {
    if lowered_name.ends_with(".drawio.xml") {
        return "drawio.xml";
    }
    match lowered_name.rfind('.') {
        Some(index) if index + 1 < lowered_name.len() => &lowered_name[index + 1..],
        _ => "",
    }
}

// Decoded icons live in thread-local storage: the resolution runs on the UI
// thread and slint::Image is not Send in this vendored renderer build.
thread_local! {
    static CACHE: RefCell<HashMap<&'static str, Image>> = RefCell::new(HashMap::new());
}

fn cached_image(cache: &RefCell<HashMap<&'static str, Image>>, key: &'static str) -> Image {
    let mut cache = cache.borrow_mut();
    if let Some(image) = cache.get(key) {
        return image.clone();
    }
    let bytes = ICON_BYTES
        .iter()
        .find(|(candidate, _)| *candidate == key)
        .map(|(_, bytes)| *bytes);
    let image = bytes.and_then(decode_png_image).unwrap_or_default();
    cache.insert(key, image.clone());
    image
}

/// Decode PNG bytes into a straight-alpha Slint image.
pub(crate) fn decode_png_image(bytes: &[u8]) -> Option<Image> {
    let mut decoder = png::Decoder::new(std::io::Cursor::new(bytes));
    decoder.set_transformations(png::Transformations::EXPAND);
    let mut reader = decoder.read_info().ok()?;
    let buffer_size = reader
        .output_buffer_size()
        .expect("output buffer size known after read_info");
    let mut buffer = vec![0u8; buffer_size];
    let info = reader.next_frame(&mut buffer).ok()?;
    let width = info.width;
    let height = info.height;
    let raw = &buffer[..info.buffer_size()];
    let mut pixels = slint::SharedPixelBuffer::<slint::Rgba8Pixel>::new(width, height);
    let out = pixels.make_mut_bytes();
    match info.color_type {
        png::ColorType::Rgba => out.copy_from_slice(raw),
        png::ColorType::Rgb => {
            for (index, pixel) in out.chunks_exact_mut(4).enumerate() {
                pixel[0] = raw[index * 3];
                pixel[1] = raw[index * 3 + 1];
                pixel[2] = raw[index * 3 + 2];
                pixel[3] = 255;
            }
        }
        png::ColorType::Grayscale => {
            for (index, pixel) in out.chunks_exact_mut(4).enumerate() {
                let value = raw[index];
                pixel[0] = value;
                pixel[1] = value;
                pixel[2] = value;
                pixel[3] = 255;
            }
        }
        png::ColorType::GrayscaleAlpha => {
            for (index, pixel) in out.chunks_exact_mut(4).enumerate() {
                let value = raw[index * 2];
                pixel[0] = value;
                pixel[1] = value;
                pixel[2] = value;
                pixel[3] = raw[index * 2 + 1];
            }
        }
        _ => return None,
    }
    Some(Image::from_rgba8(pixels))
}

#[cfg(test)]
mod tests {
    use super::icon_key;

    #[test]
    fn resolves_like_the_web_panel() {
        assert_eq!(icon_key("main.rs", "file"), "file_type_rust.png");
        assert_eq!(icon_key("notes.md", "file"), "file_type_markdown.png");
        // The web resolver maps the "toml" extension before any file-name
        // table, so even Cargo.toml shows the toml icon.
        assert_eq!(icon_key("Cargo.toml", "file"), "file_type_toml.png");
        assert_eq!(icon_key(".gitignore", "file"), "file_type_git.png");
        assert_eq!(icon_key("notes.markdown", "file"), "file_type_markdown.png");
        assert_eq!(icon_key("flow.drawio", "file"), "processon_flow.png");
        assert_eq!(icon_key("flow.drawio.xml", "file"), "processon_flow.png");
        assert_eq!(icon_key("report", "dir"), "folder.png");
        assert_eq!(icon_key("未命名", "file"), "default_file.png");
        assert_eq!(icon_key("README.", "file"), "default_file.png");
        assert_eq!(icon_key("archive.jar", "file"), "default_file.png");
    }
}
